### ISSUE TITLE
FreeFileSync recipe not working properly

### ISSUE THREAD

**Issue by jutonium** [autopkg/dataJAR-recipes#103]
The version number in the receipt has been stuck at 1.0 while the version for the app (CFBundleShortVersionString, CFBundleVersion) fits the version on the website and the naming of the downloaded ZIP-file.

Multiple versions showing the same 1.0 version in the receipts-array:
![bad_receipts_freefilesync](https://user-images.githubusercontent.com/68945137/88779175-bffd6180-d189-11ea-85e6-3ef1b9406f37.png)

**Comment by jutonium** [comment]
An installs-array created by MunkiInstallsItemsCreator during the FreeFileSync.pkg.recipe could solve the problem.

**Comment by Daz-wallace** [comment]
Hi @jutonium 
Thanks for the heads up. I've made tweaks to the .pkg and .munki recipes that should now fix this. All tested fine this side!

Give it a test and re-open if not 😊 

Thanks!

**Comment by jutonium** [comment]
Thanks! That was quick!
Now the caking on the ice would be if the minosversion (pkginfo) would be set properly as well.

**Comment by Daz-wallace** [comment]
Pull requests accepted 😊

**Comment by Daz-wallace** [comment]
I'm not sure how it's possible to pull the minimum OS Version from the Package but It'll be a minor edit to manually specify it within the recipe.

The first option would be better ideally

**Comment by Daz-wallace** [comment]
Hmm, it looks like every other recipe for Munki I can find will set the minosversion manually and not dynamically. I'll add it in now.
