### ISSUE TITLE
BoxDrive - Code: 409 Response: Conflict

### ISSUE THREAD

**Issue by nvts31** [autopkg/dataJAR-recipes#105]
Getting a 409 due to conflict in name for EA versus name for Smart Group. Names do not match, so the SG update fails.

**Exenstion Attribute:**
```
<computer_extension_attribute>
	<name>Box Drive</name>
<description />
```

**Smart Group:**
```
<criterion>
			<name>BoxVersion</name>
			<priority>1</priority>
			<and_or>and</and_or>
			<search_type>is not</search_type>
			<value>%VERSION%</value>
</criterion>
```
Also, the version info fails append to the pkg_name upload to JSS.
` 'filename': 'Box Drive.pkg',`

Cheers

**Comment by Daz-wallace** [comment]
Hi @nvts31 

I've committed some changes that should fix the issues you mention. Can you give them a test?

I'm afraid I no longer have a jssimporter setup available so if this still has issues, we may need you to log a PR.

Thanks!

**Comment by macmule** [comment]
@nvts31 I'll close this off for now.. please come back if the issue persists

**Comment by nvts31** [comment]
The fix for this SmartGroup should be the below in order to match the EA.

```
			- <name>Box Version</name>
			+ <name>Box Drive</name>
```
