### ISSUE TITLE
Consider Hardcoding QLab Sparkle Feed URL

### ISSUE THREAD

**Issue by jazzace** [autopkg/dataJAR-recipes#108]
In your QLab4.download recipe, you use an Input variable to specify the Sparkle Feed URL. About 6 months ago, you updated the recipe to change the URL in question. Those of us with an existing recipe override did not receive the benefits of the update (since the URL in our override was not updated), and since the old URL was still working (albeit stuck on a previous release), it was easy to think that the recipe was working as intended.

For this reason, I would like to ask you to consider hardcoding said URL in the body of the recipe so that any future changes are automatically passed on to recipe users who approve the updated recipe. The main reason to leave it as an Input variable is so that users can changed said URL without needing to file a pull request with the recipe owner. But since dataJAR is a company that actively maintains their recipes, having that flexibility should not be necessary.

**Comment by macmule** [comment]
@jazzace sounds like a plan.

Could you file a PR? Else we’ll get to it in due course next week.

**Comment by jazzace** [comment]
Addressed in #110 — my linter did some clean up as well, as described in the notes.
