### ISSUE TITLE
cannot import using Adobe2020Importer.py

### ISSUE THREAD

**Issue by b3to** [autopkg/dataJAR-recipes#115]
Hi, i am running Adobe2020Importer.py with the munki override and keep getting this error:

The following recipes failed:
    local.munki.AdobePhotoshop2020
        Error in local.munki.AdobePhotoshop2020: Processor: Adobe2020Versioner: Error: list index out of range

**Comment by macmule** [comment]
@b3to please see the below from step 1:

```
Build the wanted Adobe 2020 titles from the Adobe Admin Console.
Please Note: These should be of the Managed Install variety, as a Self Service package does not create the required _Uninstall.pkg which is needed by the Adobe2020Versioner.py processor. See this issue for more info.
```

**Comment by b3to** [comment]
![image](https://user-images.githubusercontent.com/23159997/96915262-0bb36480-1474-11eb-91e1-c9760b48efeb.png)

**Comment by b3to** [comment]
ok, managed to make it work. followed your instructions.
