### ISSUE TITLE
Aspera Connect deprecated

### ISSUE THREAD

**Issue by floriangeyer** [autopkg/dataJAR-recipes#121]
Is there any chance to get the Aspera Connect recipe to work again anytime soon?

**Comment by Daz-wallace** [comment]
Sure, but it'll need IBM to make changes to resolve the below:

```
                	-	Changes to the website to make scraping difficult or impossible
                	-	Downloaded item is now an installer application
```

We'll happily accept PRs to fix the above if it can be done 😊 

Thanks

**Comment by floriangeyer** [comment]
Ok, I see. That new One-Click Installer App is available without logging into IBMid. There is still a systemwide installer package, that is available when you log into IBMid though.

**Comment by Daz-wallace** [comment]
Yea there was two issues:
1) We couldn't scrap the website to pull down whatever the latest version was
2) Manually downloading the installer provided an "installer App" which aren't mass-deployable.

If you have a direct link for the first issue, that doesn't need a login, that'll help.
If the downloaded file is a proper macOS installer package (and not an App), that'll help the second issue.

We'll also happily accept PRs to fix the above if it can be done

**Comment by Daz-wallace** [comment]
Closed as there's no change here and this still isn't do-able :/

**Comment by n8felton** [comment]
This might be of use: https://d3gcli72yxqn2z.cloudfront.net/connect_latest/v4/connectversions.min.js
Appears to be JSON as a JavaScript variable. Could either use a customer processor, or scrape it.

```
{
        "title": "Aspera Connect for Mac Intel",
        "platform": {
            "os": "Mac OS X",
            "arch": "Intel",
            "version": "10.7"
        },
        "navigator": {
            "platform": "MacIntel"
        },
        "version": "3.11.1.58",
        "id": "urn:uuid:D8629AD2-6898-4811-A46F-2AF386531BFF",
        "updated": "2021-01-19T17:41:49-08:00",
        "links": [{
            "title": "Mac Intel Installer",
            "type": "application/octet-stream",
            "href": "bin/IBMAsperaConnectInstaller-3.11.1.58.dmg",
            "hreflang": "en",
            "rel": "enclosure"
        }, {
            "title": "Mac Intel Installer",
            "type": "application/octet-stream",
            "href": "bin/IBMAsperaConnectInstallerOneClick-3.11.1.58.dmg",
            "hreflang": "en",
            "rel": "enclosure-one-click"
        }, {
            "title": "Aspera Connect for Mac HTML Documentation",
            "type": "text/html",
            "href": "https://www.ibm.com/support/knowledgecenter/SSXMX3_3.11/connect_user_osx/guide.html",
            "hreflang": "en",
            "rel": "documentation"
        }, {
            "title": "Aspera Connect for Mac Release Notes",
            "type": "text/html",
            "href": "https://www.ibm.com/support/knowledgecenter/SSXMX3_3.11/connect_relnotes/3.11.1.html",
            "hreflang": "en",
            "rel": "release-notes"
        }]
} 
```
Take `href` from  `rel: enclosure`,  append it to the end of the base URL `https://d3gcli72yxqn2z.cloudfront.net/connect_latest/v4` to get `https://d3gcli72yxqn2z.cloudfront.net/connect_latest/v4/bin/IBMAsperaConnectInstaller-3.11.1.58.dmg`, and boom, you're back in business.

**Comment by Daz-wallace** [comment]
Well, that does look promising!
Thanks @n8felton I'll reopen and take a look when I can 😊

**Comment by macmule** [comment]
scraping json is easy peasy.. https://github.com/autopkg/dataJAR-recipes/blob/master/Audacity/Audacity.download.recipe

**Comment by Daz-wallace** [comment]
Just for due diligence, Where did you grab the URL (https://d3gcli72yxqn2z.cloudfront.net/connect_latest/v4/connectversions.min.js) from @n8felton ?

**Comment by n8felton** [comment]
> Just for due diligence, Where did you grab the URL (https://d3gcli72yxqn2z.cloudfront.net/connect_latest/v4/connectversions.min.js) from @n8felton ?

I went to https://www.ibm.com/aspera/connect/ and did some digging with Chrome Dev Tools into how the site generated the `Download Aspera Connect 3.11.1 for macOS` button. I will admit that the `https://d3gcli72yxqn2z.cloudfront.net` URL may change, so it might be a two-part scrape - one to scrape https://www.ibm.com/aspera/connect for the cloudfront.net host, and one to scrape the resulting `/connect_latest/v4/connectversions.min.js`

**Comment by Daz-wallace** [comment]
Awesome, I'll see what I can do 😊 
Thanks!

**Comment by Daz-wallace** [comment]
1) Scrape "https://www.ibm.com/aspera/connect/" for "https://[thing].cloudfront.net" (e.g. https://d3gcli72yxqn2z.cloudfront.net)
2) Scrape "[result from 1]/connect_latest/v4/connectversions.min.js" for "/bin/IBMAsperaConnectInstaller-[version].dmg" (e.g. "/bin/IBMAsperaConnectInstaller-3.11.1.58.dmg")
3) Use "[result from 1]/connect_latest/v4/[result from 2]" for download
4) Profit!

**Comment by Daz-wallace** [comment]
Resolved and back in a usable state after the above commit. Big thanks to @n8felton for the hard work!

**Comment by macmule** [comment]
@it-insight, please see https://github.com/autopkg/dataJAR-recipes/issues/167

**Comment by dwosk** [comment]
@macmule @symmtree @Daz-wallace @n8felton @floriangeyer 

I'm one of the developers on the Aspera Connect team here at IBM. I'm actually working on a new PKG installer currently - I'd love some feedback and to know what would make it easier for you to use. Shoot me an email (dwosk@us.ibm.com) if you want.

**Comment by paul-cossey** [comment]
Morning, @dwosk

Thanks for the offer of help! We're having some issues scraping a URL again, I've just emailed you with the details. 

Thanks, 
Paul

**Comment by paul-cossey** [comment]
Thanks for your help, @dwosk :-)

Resolved with this commit: https://github.com/autopkg/dataJAR-recipes/commit/4de271ef81ea16f43eaf92b8560ba901f7f7361e
