### ISSUE TITLE
DisplayLink.munki.recipe - pulling legacy releases

### ISSUE THREAD

**Issue by ewtillman** [autopkg/dataJAR-recipes#122]
Technically this is not broken as it pulls the old DisplayLink USB Graphics Software Release 5.2.5" but their new driver "DisplayLink Manger Graphics Release 1.1" software is required for MacOS 11/10.15
Just wondering if you had any plans on updating this?

**Comment by neilmartin83** [comment]
Hi @ewtillman ,

I'd recommend using the DisplayLink Manager recipes from the smithjw-recipes repo. Our recipes intentionally download the driver. I've updated the description of the Download recipe to clarify this but we won't be making any further changes.

Many thanks!
