### ISSUE TITLE
Downloading Crashplan 6

### ISSUE THREAD

**Issue by jonbrown21** [autopkg/dataJAR-recipes#13]
When using the .munki recipe which leverages your download recipe I get the following error

Processing CrashPlan for Enterprise 6.munki.recipe...
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.

`Processing CrashPlan for Enterprise 6.munki.recipe...
URLTextSearcher
{'Input': {'re_pattern': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_+[0-9]+\\.+[0-9]+\\.+[0-9]+\\_Mac.dmg',
           'url': u'https://support.code42.com/Administrator/6/Planning_And_Installing/Code42_server_and_app_downloads'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (match): https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg
{'Output': {'match': 'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'CrashPlanForEnterprise6.dmg',
           'url': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.
Receipt written to /Users/serveradmin/Library/AutoPkg/Cache/local.munki.CrashPlan for Enterprise 6/receipts/CrashPlan for Enterprise 6.munki-receipt-20180731-143612.plist

The following recipes failed:
    CrashPlan for Enterprise 6.munki.recipe
        Error in local.munki.CrashPlan for Enterprise 6: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)`

**Comment by macmule** [comment]
Working here

```
URLTextSearcher
{'Input': {'re_pattern': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_+[0-9]+\\.+[0-9]+\\.+[0-9]+\\_Mac.dmg',
           'url': u'https://support.code42.com/Administrator/6/Planning_And_Installing/Code42_server_and_app_downloads'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (match): https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg
{'Output': {'match': 'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'CrashPlanForEnterprise 6.dmg',
           'url': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Wed, 09 May 2018 15:22:34 GMT
URLDownloader: Storing new ETag header: "5af3123a-7dfcaf9"
URLDownloader: Downloaded /Users/btoms/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg
{'Output': {'download_changed': True,
            'etag': '"5af3123a-7dfcaf9"',
            'last_modified': 'Wed, 09 May 2018 15:22:34 GMT',
            'pathname': u'/Users/btoms/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg',
            'url_downloader_summary_result': {'data': {'download_path': u'/Users/btoms/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg'},
                                              'summary_text': 'The following new items were downloaded:'}}}
EndOfCheckPhase

```

**Comment by macmule** [comment]
Proxy?

The URL is correct: https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg

**Comment by jonbrown21** [comment]
Strange, not using a proxy here so not sure why its not working for me. I tested the download and was able to get the DMG. But when I run the .munki recipe it fails. 

`URLTextSearcher
{'Input': {'re_pattern': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_+[0-9]+\\.+[0-9]+\\.+[0-9]+\\_Mac.dmg',
           'url': u'https://support.code42.com/Administrator/6/Planning_And_Installing/Code42_server_and_app_downloads'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (match): https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg
{'Output': {'match': 'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'CrashPlanForEnterprise 6.dmg',
           'url': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Wed, 09 May 2018 15:22:34 GMT
URLDownloader: Storing new ETag header: "5af3123a-7dfcaf9"
URLDownloader: Downloaded /Users/serveradmin/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg
{'Output': {'download_changed': True,
            'etag': '"5af3123a-7dfcaf9"',
            'last_modified': 'Wed, 09 May 2018 15:22:34 GMT',
            'pathname': u'/Users/serveradmin/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg',
            'url_downloader_summary_result': {'data': {'download_path': u'/Users/serveradmin/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg'},
                                              'summary_text': 'The following new items were downloaded:'}}}
EndOfCheckPhase
{'Input': {}}
{'Output': {}}
CodeSignatureVerifier
{'Input': {'expected_authority_names': (
    "Developer ID Installer: Code 42 Software (9YV9435DHD)",
    "Developer ID Certification Authority",
    "Apple Root CA"
),
           'input_path': u'/Users/serveradmin/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg/Install Code42 CrashPlan.pkg'}}
CodeSignatureVerifier: Mounted disk image /Users/serveradmin/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg
CodeSignatureVerifier: Verifying installer package signature...
CodeSignatureVerifier: Package "Install Code42 CrashPlan":
CodeSignatureVerifier:    Status: signed by a certificate trusted by Mac OS X
CodeSignatureVerifier:    Certificate Chain:
CodeSignatureVerifier:     1. Developer ID Installer: Code 42 Software (9YV9435DHD)
CodeSignatureVerifier:        SHA1 fingerprint: 17 75 48 D5 19 59 83 5A 36 42 6D 7F C4 8C A3 45 FE 3C F0 1C
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     2. Developer ID Certification Authority
CodeSignatureVerifier:        SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
CodeSignatureVerifier:        -----------------------------------------------------------------------------
CodeSignatureVerifier:     3. Apple Root CA
CodeSignatureVerifier:        SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60
CodeSignatureVerifier: 
CodeSignatureVerifier: Signature is valid
CodeSignatureVerifier: Authority name chain is valid
{'Output': {}}
Receipt written to /Users/serveradmin/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/receipts/CrashPlan for Enterprise 6.download-receipt-20180731-160804.plist

The following new items were downloaded:
    Download Path                                                                                                                                   
    -------------                                                                                                                                   
    /Users/serveradmin/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise 6.dmg  `

`Processing CrashPlan for Enterprise 6.munki.recipe...
URLTextSearcher
{'Input': {'re_pattern': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_+[0-9]+\\.+[0-9]+\\.+[0-9]+\\_Mac.dmg',
           'url': u'https://support.code42.com/Administrator/6/Planning_And_Installing/Code42_server_and_app_downloads'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
URLTextSearcher: Found matching text (match): https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg
{'Output': {'match': 'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'CrashPlanForEnterprise6.dmg',
           'url': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.
Receipt written to /Users/serveradmin/Library/AutoPkg/Cache/local.munki.CrashPlan for Enterprise 6/receipts/CrashPlan for Enterprise 6.munki-receipt-20180731-160903.plist

The following recipes failed:
    CrashPlan for Enterprise 6.munki.recipe
        Error in local.munki.CrashPlan for Enterprise 6: Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)`

**Comment by jonbrown21** [comment]
Just spotted something this bit of code in the downloader

'filename': u'CrashPlanForEnterprise 6.dmg',

is different from the bit in the Munki Recipe

'filename': u'CrashPlanForEnterprise6.dmg',

could that have anything to do with anything?

**Comment by jonbrown21** [comment]
That was it. I changed

```
<key>NAME</key>
		<string>CrashPlanForEnterprise6</string>
```

to

```
<key>NAME</key>
		<string>CrashPlanForEnterprise 6</string>
```

and it started working. Odd that it just started throwing errors. If you can replicate this behavior I am happy to submit a pull request.

**Comment by macmule** [comment]
Still working for me.. (.download & .munki)

NAME is a variable, so whilst untidy it won't cause issues.

The CURL download is still failing, but the URL looks fine.

```
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'CrashPlanForEnterprise6.dmg',
           'url': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
Curl failure: The requested URL returned error: 404 Not Found (exit code 22)
Failed.
```

And still working here.
```
URLDownloader
{'Input': {'CURL_PATH': '/usr/bin/curl',
           'filename': u'CrashPlanForEnterprise6.dmg',
           'url': u'https://download.code42.com/installs/mac/install/Code42CrashPlan/Code42CrashPlan_6.7.2_Mac.dmg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: Storing new Last-Modified header: Wed, 09 May 2018 15:22:34 GMT
URLDownloader: Storing new ETag header: "5af3123a-7dfcaf9"
URLDownloader: Downloaded /Users/btoms/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise6.dmg
{'Output': {'download_changed': True,
            'etag': '"5af3123a-7dfcaf9"',
            'last_modified': 'Wed, 09 May 2018 15:22:34 GMT',
            'pathname': u'/Users/btoms/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise6.dmg',
            'url_downloader_summary_result': {'data': {'download_path': u'/Users/btoms/Library/AutoPkg/Cache/com.github.dataJAR-recipes.munki.CrashPlan for Enterprise 6/downloads/CrashPlanForEnterprise6.dmg'},
                                              'summary_text': 'The following new items were downloaded:'}}}
EndOfCheckPhase

```

**Comment by jonbrown21** [comment]
Strange, ok well I will close this out. The change fixes the issue that I had on my end. I will ping you back if something more concrete happens.
