### ISSUE TITLE
Adobe 2020 Apps have changed the minimum OS

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#138]
Hey folks,

Looks like Adobe have changed the minimum macOS version from 10.13 to 10.14 in the middle of the 2020 versions, e.g.:
- After Effects 2020 v17.5 installs on macOS 10.13, v17.7 doesn't
- Media Encoder v14.5 installs on macOS 10.13, v14.9 doesn't

Adobe did warn of this but it was taken for new _major_ version changes, not a minor OS update:

> Upcoming changes to operating system support
> Effective in January 2021, new releases of the Creative Cloud video and audio applications will require macOS 10.14 (or later) or Windows 10 v1903 (or later).
> This is in keeping with our policy to support the current and the most recent previous version of each operating system, which allows us to focus our resources on modern architectures. 
https://helpx.adobe.com/media-encoder/user-guide.html/media-encoder/system-requirements.ug.html 

For now we've made a quick change to edit the minimum OS version in the Adobe 2020 recipe. Longer term, we'll look to pull this direct from the packages.

**Comment by macmule** [comment]
So.. digging into this.. the Min OS Version isn't stated in the same place for each pkg etc..

1. For most apps, we can try the info.plist.. but not all have it.
2. Others were it's missing or the info.plist etc is in a odd format we can check the application.json
3. But apps like Acrobat.. it's in the pkg payload of the .app, and is like the below.

```
	<key>LSMinimumSystemVersion</key>
	<string>10 . 4 . 3</string>
```

I guess the actual version is within the 635 scripts in the pkg...

<img width="1022" alt="Screenshot 2021-03-23 at 14 59 40" src="https://user-images.githubusercontent.com/2464974/112171332-9f3bbd80-8beb-11eb-9ff8-7c96713604d6.png">

So.. we'll keep it in the override
