### ISSUE TITLE
Google Backup and Sync recipe broken due to parent recipe name change?

### ISSUE THREAD

**Issue by samuryan89** [autopkg/dataJAR-recipes#14]
Hi there, trying to use your ["Google Backup and Sync.munki.recipe"](https://github.com/autopkg/dataJAR-recipes/blob/master/Google%20Backup%20and%20Sync/Google%20Backup%20and%20Sync.munki.recipe) with AutoPKG, but it's not able to find a parent recipe.

I think line 38...
<string>com.github.nstrauss.download.BackupandSync</string>

...needs to be updated, but not entirely sure with what. The new location is here:
https://github.com/autopkg/nstrauss-recipes/blob/master/Google%20Backup%20and%20Sync/GoogleBackupandSync.download.recipe

Thanks!

**Comment by macmule** [comment]
@samuryan89 all working here.

Do you have nstrauss's recipe repo added to your AutoPkg?

**Comment by macmule** [comment]
Alrighty.. closing this off..

Reopen if needed :)
