### ISSUE TITLE
CrashPlan for Enterprises Recipe failing.

### ISSUE THREAD

**Issue by oliverweinm** [autopkg/dataJAR-recipes#147]
Currently, the the CrashPlan for Enterprises.pkg recipe fails, causing the CrashPlan for Enterprises.munki recipe to fail too:

Error message:
The following recipes failed:
    CrashPlan for Enterprise 6.munki.recipe
        Error in local.munki.CrashPlan for Enterprise 6: Processor: FlatPkgUnpacker: Error: extraction of /Users/setup/Library/AutoPkg/Cache/local.munki.CrashPlan for Enterprise 6/unpack/ with pkgutil failed: Could not open package for expansion: /Users/setup/Library/AutoPkg/Cache/local.munki.CrashPlan for Enterprise 6/unpack/

I have fixed the underlying error in this PR: https://github.com/autopkg/dataJAR-recipes/pull/146

**Comment by macmule** [comment]
ty, PR merged :)
