### ISSUE TITLE
Audacity recipe failing

### ISSUE THREAD

**Issue by ian-atkinson** [autopkg/dataJAR-recipes#150]
Hi,

The Audacity recipe in this repo doesn't seem to work at the moment, the download URL (e.g. https://university.fosshub.com/Protected/5b7eee97e8058c20a7bbfcf4/607d5ff6abcf810357b72497/audacity-macos-3.0.2.dmg) is a 403

Ian

**Comment by Daz-wallace** [comment]
Hi @ian-atkinson 

Have you followed through the notes from the download recipe?


> All users should contact FossHub directly (https://www.fosshub.com/contact.html) to seek permission to use an automated tool for the purpose of redistributing this software on their internal network, as specified in their Terms of Service (https://www.fosshub.com/tos.html#fh-tou-o7).     You will need to provide them the IP address of the machine downloading FossHub software.     This recipe does not perform any tracking (cookies, advertising identifiers, and similar technologies) and respects the EU General Data Protection Regulation (GDPR) guidelines.    This recipe downloads the latest Audacity dmg.    For more information see: https://macmule.com/2019/03/17/fosshub-autopkg

**Comment by ian-atkinson** [comment]
Ah, no I didn't sorry! I will get that set up,

Ian

**Comment by macmule** [comment]
@ian-atkinson any better after reaching out to fosshub?

**Comment by ian-atkinson** [comment]
Hi,

I didn't hear back from them yet but I'm sure that will sort it,

Ian

**Comment by macmule** [comment]
@ian-atkinson, ok, i'll close this off.. feel free to re-open if still an issue.
