### ISSUE TITLE
Anaconda 3 installcheck_script white space?

### ISSUE THREAD

**Issue by eshirk** [autopkg/dataJAR-recipes#151]
First, thanks for taking over the Anaconda3.munki.recipe from ygini-recipes!

However, I'm struggling with the installcheck_script, and I think it's due to Python white space issues. I've tried various approaches to resolve it but with no luck.

**Comment by macmule** [comment]
@eshirk sorry, what issues are you seeing?

**Comment by eshirk** [comment]
Let me create a clean override (this one has been kicked around too much) and I'll get back to you.

**Comment by eshirk** [comment]
My bad--not your recipe at all, but one of the parent recipe (hansen-m) processors (MunkiPkginfoMerger). Apologies for the noise, closing this request.
