### ISSUE TITLE
Mismatched </array> tag in Suitcase Fusion 7.munki.recipe

### ISSUE THREAD

**Issue by mtconleyuk** [autopkg/dataJAR-recipes#161]
WARNING: plist error for /Users/admin/Library/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes/Suitcase Fusion 7/Suitcase Fusion 7.munki.recipe: mismatched tag: line 96, column 6

**Comment by macmule** [comment]
thanks, should be sorted now @mtconleyuk
