### ISSUE TITLE
Recipe for Apple Silicon Version of Box Drive

### ISSUE THREAD

**Issue by minorsatellite** [autopkg/dataJAR-recipes#168]
The current versions of the Box Munki recipe is for Intel only. Is there any chance that a recipe for the Beta release will be available any time soon?

**Comment by macmule** [comment]
So.. we typically don't create recipes for betas.. but I had a look to see if this would be an easy thing to accommodate.. and sadly it's not.

The Box Drive recipes scrapes https://www.box.com/en-gb/resources/downloads for the download url of the pkg, only the intel pkg is available on that page.

There is a link on that page for the Silicon release, which is: https://support.box.com/hc/en-us/articles/1500004479962-Box-Drive-support-on-devices-with-M1-chips and this then links to https://support.box.com/hc/en-us/articles/4404386710419 which holds the url for the pkg.

So, it's not something we can simply add as it's not a little regex change to the TextSearcher.
