### ISSUE TITLE
Geekbench 5 recipe curl error: SSL cert expired 

### ISSUE THREAD

**Issue by jw-macworks** [autopkg/dataJAR-recipes#169]
More of an FYI than an issue with the recipe.

https://www.primatelabs.com/appcast/geekbench5.xml

Cert info
*.primatelabs.com
Issued by: Sectigo RSA Domain Validation Secure Server CA
Expired: Tuesday, August 31, 2021 at 4:59:59 PM Pacific Daylight Time

**Comment by macmule** [comment]
@jw-macworks looks to be working now,, thanks for the headsup :)
