### ISSUE TITLE
OpenJDK 17 - change of download name and Apple Silicon release

### ISSUE THREAD

**Issue by robertryansqub** [autopkg/dataJAR-recipes#171]
With JDK 17 the naming convention for the OpenJDK downloads has changed. It's now openjdk-version_macos-x64 instead of openjdk-version_osx-x64 - which is a simple change to the re_pattern.

There is, of course, also now an Apple Silicon build. Again, a simple change to the re_pattern, but that presumably involves splitting the .download recipe into Intel and ARM variants?

**Comment by macmule** [comment]
Thanks @robertryansqub, should be sorted now.. as per https://github.com/autopkg/dataJAR-recipes/commit/a59050e8c0946a592a4f946da876f9953dcdeb6b
