### ISSUE TITLE
DisplayLink download recipe fails due to changed download webpage

### ISSUE THREAD

**Issue by eithor** [autopkg/dataJAR-recipes#173]
DisplayLink download recipe (com.github.dataJAR-recipes.download.DisplayLink) fails to download.

Regex fails to find an URL.

Observations:
The download URL 
https://www.displaylink.com/downloads 

now redirects here: 
https://www.synaptics.com/products/displaylink-graphics/downloads/macos

The regex needs to match the following on that page:
```
Release: 1.5 | <time datetime="00Z">Sep 8, 2021</time>
</p>
</div>
<div class="right-driver">
        <a href="/node/4041?filetype=exe" class="download-link">Download</a><br>
```

The download URL then becomes:
https://www.synaptics.com/node/4041?filetype=exe

This goes to an "accept EULA page":
https://www.synaptics.com/products/displaylink-graphics/downloads/macos-connectivity-1.5?filetype=exe

Which has an "Accept" button and I assume some JavaScript to start the actual download.

If I replace the regex in URLTextSearcher with:

`href="/node/(\d+)\?filetype=exe"`

and DOWNLOAD_URL with:
https://www.synaptics.com/products/displaylink-graphics/downloads

and change the URLDownloader processor to have:
```
<key>url</key>
<string>%DOWNLOAD_URL2%/%match%?filetype=exe</string>
```

where DOWNLOAD_URL2 is 
https://www.synaptics.com/node

I get curl to find the correct 4041 match, but on curl download I get the web-page with the EULA text instead of the pkg.

**Comment by macmule** [comment]
https://github.com/autopkg/dataJAR-recipes/blob/master/DisplayLink/DisplayLink.download.recipe#L21-L29

We deprecated the recipe as no longer downloadable a week ago, please try the recommended recipe.
