### ISSUE TITLE
Download URL for Figma has changed

### ISSUE THREAD

**Issue by grg21de** [autopkg/dataJAR-recipes#178]
Hello there,

I think the Download URL for Figma has changed to
https://www.figma.com/download/desktop/mac

can this pls be reviewed/changed?

Thx

**Comment by macmule** [comment]
@grg21de that URL seems to download an older version, as it was updated in June vs the URL in the recipe which downloads a title which was updated in October.

**Comment by grg21de** [comment]
I see, but the Figma Recipe seems not to work as intended, at least in my environment:


`Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://desktop.figma.com/mac/%NAME%.zip', '--fail', '--output', '/Users/vankann/Library/AutoPkg/Cache/local.munki.Figma/downloads/tmp78fjt5ef']' returned non-zero exit status 22.



Failed.`

This is my Terminal Output when running autopkg.

Cheers

**Comment by macmule** [comment]
@grg21de I'm not sure what to advise here.. the recipe works here.. so there must be something local..

I'll close this one off and good luck!
