### ISSUE TITLE
Audacity download failed

### ISSUE THREAD

**Issue by mikeknight85** [autopkg/dataJAR-recipes#182]
Error in com.github.dataJAR-recipes.download.Audacity: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://university.fosshub.com/Protected/5b7eee97e8058c20a7bbfcf4/617a79633af10152701eebbd/audacity-macos-3.1.0-Intel.dmg', '--fail', '--output', 'Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.Audacity/downloads/tmpmee5xcs4']' returned non-zero exit status 22.

**Comment by macmule** [comment]
@mikeknight85 did you follow the steps in the description?

https://github.com/autopkg/dataJAR-recipes/blob/master/Audacity/Audacity.download.recipe#L5-L11

**Comment by macmule** [comment]
@mikeknight85 This will likely be sorted with the above steps being followed.. if not.. re-open
