### ISSUE TITLE
Suitcase recipe needs updates please (infos inside)

### ISSUE THREAD

**Issue by pexner** [autopkg/dataJAR-recipes#185]
Hi. Could you please update the Suitcase Fusion recipe?
DL URL: `http://bin.extensis.com/SuitcaseFusion-M-22-0-0.dmg`
Needs also a postinstall-script to install the included PlugIns:
```
#!/bin/sh
/Applications/Suitcase\ Fusion.app/Contents/Resources/plugin-installer --install-all
exit 0
```
Thanks in advance,

Patrick

**Comment by macmule** [comment]
Added - https://github.com/autopkg/dataJAR-recipes/tree/master/Suitcase%20Fusion%2022

Let us know if any issues.
