### ISSUE TITLE
Enhancement Tweak for Adobe Import 2021.munki.recipe

### ISSUE THREAD

**Issue by walkintom** [autopkg/dataJAR-recipes#186]
Would it be viable to change `<key>unattended_install</key>` and `<key>unattended_uninstall</key>` from `true` to `false`? As `<key>RestartAction</key>` is already set to `RequireLogout`, that voids the unattended install and uninstall keys being set to true.

https://github.com/autopkg/dataJAR-recipes/blob/d3b47c5060526e0b0990dd24ea7e04387d08e239/Adobe%202021/Adobe%202021%20Import.munki.recipe#L45

**Comment by macmule** [comment]
https://github.com/munki/munki/wiki/Supported-Pkginfo-Keys

```
unattended_install | boolean | If true, Munki can attempt to install this item without notifying the user. Note: this is an optional key. Setting it to false is the same as omitting the key altogether.

unattended_uninstall | boolean | If true, Munki can attempt to uninstall this item without notifying the user. Note: this is an optional key. Setting it to false is the same as omitting the key altogether.

```

Might as well remove altogether

**Comment by macmule** [comment]
Done!
