### ISSUE TITLE
UssAgent.download.recipe is failing with a 404

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#19]
Issue is with the vender, the latest version served is different from the version number of the directory it's in.

The latest directory is "4.2.2.3987" but the installer inside is "UssAgent 4.2.3.4018.dmg" (the version is wrong!)

**Comment by Daz-wallace** [comment]
Vender support emailed.

**Comment by macmule** [comment]
Seems resolved now
