### ISSUE TITLE
With Adobe 2022 packages Lightroom (non-classic) fails to lookup SAP code

### ISSUE THREAD

**Issue by everetteallen** [autopkg/dataJAR-recipes#193]
Apple Silicon version
The following recipes failed:
    local.jss.Adobe_Lightroom_2021_amac
        Error in local.jss.Adobe_Lightroom_2021_amac: Processor: Adobe2021Versioner: Error: Checking app_json for version details but sap code LRCC, is not within the known list of apps which we know to check via their Application.json

The Apple Intel version same error
    local.jss.Adobe_Lightroom_2021_mac
        Error in local.jss.Adobe_Lightroom_2021_mac: Processor: Adobe2021Versioner: Error: Checking app_json for version details but sap code LRCC, is not within the known list of apps which we know to check via their Application.json

The versioner has exception code for LightRoom but it's not clear if that is the issue.

**Comment by macmule** [comment]
@everetteallen so is this a 2021 version or 2022?

**Comment by everetteallen** [comment]
2022 just running under the "old" recipe name

**Comment by macmule** [comment]
ok.. so sort of related to #192 and really not an issue with the 2021 recipes, more than we need to update for 2022.
