### ISSUE TITLE
Postman now offers both x64 and ARM64 binaries (at least as of 9.4.0)

### ISSUE THREAD

**Issue by fseesink** [autopkg/dataJAR-recipes#194]
More of a question than an issue.

Currently the Postman munki recipe is pulling down the Intel x64 binary only. Starting with Postman v9.4.0, I noticed they have both x64 and ARM64 specific binaries.

I was just wondering if you intend to add support for the ARM64 binaries?

The current `Postman.download.recipe` uses the downoad URL:

`https://dl.pstmn.io/download/latest/osx`

But looking at this page on the Postman site:  https://www.postman.com/downloads/

and checking the buttons for the [Mac Intel Chip] and [Mac Apple Chip], I see the URLS are

`https://dl.pstmn.io/download/latest/osx_64`

and

`https://dl.pstmn.io/download/latest/osx_arm64`

respectively, in case that helps.

**Comment by paul-cossey** [comment]
Hi, @fseesink 

This has been resolved in commit: https://github.com/autopkg/dataJAR-recipes/commit/885ab794db5007bb8d83fd2aa06edbdde3f5b9f7
