### ISSUE TITLE
Update Miro to include arm64 option

### ISSUE THREAD

**Issue by redshirtdave** [autopkg/dataJAR-recipes#195]
Miro now offer seperate builds for x64 and arm64. Please add option to specify which build is required.

Download website: https://miro.com/apps/
x64: https://desktop.miro.com/platforms/darwin-arm64/Miro.dmg
arm64: https://desktop.miro.com/platforms/darwin-arm64/Miro.dmg

Thanks :)

**Comment by paul-cossey** [comment]
Hi, @redshirtdave 

The download recipe already had a url variable, but I've updated the description with the url's to use for x86_64 and arm_64 to make things clearer.

https://github.com/autopkg/dataJAR-recipes/commit/72eb29f837ab1de109c093f95f1a8eec5ddfc30a
