### ISSUE TITLE
Suitcase fusion recipe not picking up latest updates

### ISSUE THREAD

**Issue by duel007** [autopkg/dataJAR-recipes#2]
Pulls incorrect user facing version number of 18.2.2 even though release notes show 18.2.4

https://sparkle.extensis.com/u/ST/EN/suitcase18en.xml - 18.2.2 listed

https://www.extensis.com/downloads/release-notes/suitcase-fusion-7/?sparkle - 18.2.4 listed

Not sure if this is a failure of the recipe or Extensis not updating their webite.

**Comment by macmule** [comment]
@duel007 this might be like VLC, where the devs update the sparkle feed behind the general release.

I'll leave it for a week & we can then see.

**Comment by duel007** [comment]
Looks like I'm just impatient. Feed just updated and pulled latest. I think we are good. Thank you!
