### ISSUE TITLE
Code42 now has separate Intel and Apple Silicon downloads

### ISSUE THREAD

**Issue by flammable** [autopkg/dataJAR-recipes#202]
Hey hey! Just following up from a Slack discussion with @macmule - Code42 8.8.2 is out now, and there are two separate downloads for Intel and Apple Silicon. The Intel one is the same:

`https://download.code42.com/installs/agent/latest-mac.dmg`

The Apple Silicon one is new:

`https://download.code42.com/installs/agent/latest-mac-arm64.dmg`

Would it be possible to split the AutoPkg recipes to handle both? Thanks!

**Comment by mikedowler** [comment]
Could we just move the URL into a variable?  That way, we could override it in our recipes if we wanted.  I think the hope is the Code42 will see the error of their ways and start producing a universal installer pretty soon, so it makes sense to stick with a single recipe if we can.

**Comment by flammable** [comment]
From the feedback in the Slack channel so far, it sounds like they're pushing forward with separate installers. :( 

That said, if the URL was a variable, could I just create two overrides? One for Intel, and one for Apple Silicon? I'd need to set the `supported_architectures` pkginfo key for each, too (since I use Munki). If that's the case, I think that'd be a good solution.

**Comment by macmule** [comment]
@paul-cossey, wasn't this sorted?

**Comment by flammable** [comment]
Thanks, I see the arm64 recipes now!

Probably not a bad idea to add `supported_architectures` to the Intel one. I did that in my override. Both recipes work great!

**Comment by paul-cossey** [comment]
Resolved by https://github.com/autopkg/dataJAR-recipes/commit/d1855b38ce0f8adf3fa41840e2d6ce9906da088e
