### ISSUE TITLE
Switch back to Anaconda.download recipe

### ISSUE THREAD

**Issue by eshirk** [autopkg/dataJAR-recipes#203]
Per  PR #189, please switch back to using the original Anaconda.download parent recipe (https://github.com/autopkg/hansen-m-recipes/issues/206). Thanks!

**Comment by flammable** [comment]
Thanks, just ran into this, too. Here's the current location of the .download recipe:

https://github.com/autopkg/hansen-m-recipes/blob/master/Continuum/Anaconda.download.recipe

**Comment by ygini** [comment]
Same issue here

**Comment by nstrauss** [comment]
+1

Adding a comment here to push for getting https://github.com/autopkg/dataJAR-recipes/pull/208 merged.

**Comment by paul-cossey** [comment]
Thanks for the PR @hfike 

Resolved with https://github.com/autopkg/dataJAR-recipes/commit/6ee8d037da7a00a1fcae97e517c3118bff043e07
