### ISSUE TITLE
Error in com.github.dataJAR-recipes.download.Wondershare Filmora X: Processor: CodeSignatureVerifier: Error: Error processing path '/private/tmp/dmg.EZflP7/Wondershare Filmora X.app' with glob.

### ISSUE THREAD

**Issue by macmule** [autopkg/dataJAR-recipes#205]
Now an installer app
<img width="752" alt="Screenshot 2022-02-23 at 13 47 04" src="https://user-images.githubusercontent.com/2464974/155333759-4178063c-749a-4cd3-8d63-18b7f0bdb394.png">

**Comment by paul-cossey** [comment]
Resolved with:  https://github.com/autopkg/dataJAR-recipes/commit/eb4a214916d97e249553281328962f4774528d30
