### ISSUE TITLE
Apache NetBeans

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/dataJAR-recipes#211]
Apache NetBeans 12 is now on Apache NetBeans 13, but there isn't an available installer for macOS yet. 

https://netbeans.apache.org/download/nb13/nb13.html

**Comment by macmule** [comment]
@paul-cossey 13 is now there :)

**Comment by paul-cossey** [comment]
Apache NetBeans 12 pointed to the v12 archive and new v13 Recipes have been created 

https://github.com/autopkg/dataJAR-recipes/tree/master/Apache%20NetBeans%2013
