### ISSUE TITLE
Suitcase Fusion is now Connect Fonts Powered By Suitcase

### ISSUE THREAD

**Issue by prausch** [autopkg/dataJAR-recipes#219]
The Sparkle URL is just incremented to 23 from 22, but putting that in an override doesn't work, as the application name has changed, I assume.

**Comment by paul-cossey** [comment]
Hi, @prausch 

Thanks, for this. Yeah the change in name will effect the recipes. 

I've just created some new ones for Connect Fonts here: https://github.com/autopkg/dataJAR-recipes/tree/master/Connect%20Fonts

Thanks
Paul
