### ISSUE TITLE
VIA.download.recipe grabbing old version

### ISSUE THREAD

**Issue by uisge-beatha** [autopkg/dataJAR-recipes#22]
Hello, 

When I took a look at VIA.pkg this morning it was producing a pkg for version 2.3, rather than 2.4 as expected. I took a look at VIA.download.recipe and found it was pointing to what seems to be a dedicated page for version 2.3.  Two changes to VIA.download.recipe fixed the issue for me:

I changed the URL argument in URLTextSearcher to this location: https://k.kramerav.com/support/download.asp?f=55519

This necessitated a change to the URL argument in URLDownloader. This worked for me: https://cdn.kramerav.com/web%match%

**Comment by macmule** [comment]
@uisge-beatha thanks, can you file a PR?

**Comment by uisge-beatha** [comment]
Done!

**Comment by macmule** [comment]
Awesome, thanks & merged!

https://github.com/autopkg/dataJAR-recipes/pull/23
