### ISSUE TITLE
Ultimaker Cura

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/dataJAR-recipes#224]
Info.plist doesn't have the correct versioning info in.

Issue has been raised with the vendor here: https://github.com/Ultimaker/Cura/issues/12474

**Comment by paul-cossey** [comment]
5.1 is in Beta - checked the `Info.plist` and it's still showing the `CFBundleShortVersionString` as version `0.0.0`

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDisplayName</key>
	<string>Ultimaker-Cura</string>
	<key>CFBundleExecutable</key>
	<string>Ultimaker-Cura</string>
	<key>CFBundleIconFile</key>
	<string>cura.icns</string>
	<key>CFBundleIdentifier</key>
	<string>nl.ultimaker.cura</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Ultimaker-Cura</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.0.0</string>
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
```

**Comment by paul-cossey** [comment]
The versioning _should_ be fixed in the next stable release. 

https://github.com/Ultimaker/Cura/commit/c100f68f58d0c39b9f6b70df32edb2a4b3ca40c6

**Comment by MLBZ521** [comment]
The app itself was fixed, but they changed the plist key that contains the version so the recipe is still broken.  I just submitted #236 to fix that.
