### ISSUE TITLE
Citrix Files for Mac.pkg has a problem for downstream processors.

### ISSUE THREAD

**Issue by Honestpuck** [autopkg/dataJAR-recipes#225]
The recipe uses the FileMover processor to rename the package from `Citrix Files for Mac.pkg` to `Citrix Files for Mac-24.4.pkg` (or other version number). That processor doesn’t update the `pkg_path` variable so there is a version number in the new file name but not in  `pkg_path`. This causes problems for downstream processors such as my `JPCImporter` or Graham Pugh's `JamfUploader` 

Replace `FileMover` with `PkgCopier` and it all works.

Here is the replacement Processor:

```
		<dict>
			<key>Processor</key>
			<string>PkgCopier</string>
			<key>Arguments</key>
			<dict>
				<key>source_pkg</key>
				<string>%pkg_path%</string>
				<key>pkg_path</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%-%version%.pkg</string>
			</dict>
		</dict>
```

The downside is you have two copies of the pkg file left in Cache but that doesn't upset anything. If you really wanted you could add a `PkgDeleter` processor step after `PkgCopier` to fix that problem.

**Comment by Honestpuck** [comment]
I actually found 6 `.pkg` recipes in the repo with this problem. Give me a few days and I will submit a PR.

**Comment by macmule** [comment]
@Honestpuck tbh, we don't use the jamf or many of the pkg recipes and are long term looking to remove.

We could deprecate them and you take them on?

Alternately, you could use the [FileFinder](https://github.com/autopkg/autopkg/wiki/Processor-FileFinder) processor to find the pkg's in the upstream recipes.

**Comment by Honestpuck** [comment]
OK. I will fix it locally in the recipe I'm using.
