### ISSUE TITLE
Figma recipe download ARM version

### ISSUE THREAD

**Issue by adrienlabigne** [autopkg/dataJAR-recipes#227]
Hello,

The download recipe systematically takes the ARM version while the recipe does not specify the version.

<dict>
		<key>NAME</key>
		<string>Figma</string>
		<key>url</key>
		<string>https://desktop.figma.com/mac-arm/Figma.zip</string>
</dict>

It would be appropriate to make an ARM version and an Intel version no?

Thanks

**Comment by paul-cossey** [comment]
Hi, @adrienlabigne 

The [Figma download recipe](https://github.com/autopkg/dataJAR-recipes/blob/master/Figma/Figma.download.recipe) has support for downloading both arm64 and x86_64 versions via the url variable. 

You can specify which you'd like to download in your override. 

```
<dict>
	<key>Description</key>
	<string>Downloads the current release version of Figma.
		url for x86: https://desktop.figma.com/mac/Figma.zip
		url for arm64: https://desktop.figma.com/mac-arm/Figma.zip
	</string>
	<key>Identifier</key>
	<string>com.github.dataJAR-recipes.download.Figma</string>
	<key>Input</key>
	<dict>
		<key>NAME</key>
		<string>Figma</string>
		<key>url</key>
		<string>https://desktop.figma.com/mac-arm/Figma.zip</string>
	</dict>
```
