### ISSUE TITLE
Code42

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/dataJAR-recipes#228]
The Code42 download recipe is pulling down version 8 and isn't pulling down the most recent version which is 10.

Version 10 is currently only available from behind a login window.

**Comment by flammable** [comment]
So, things have changed a bit. Code42 split off its backup product into a new company, called CrashPlan. Right now, the Code42 app is used by both companies - version 10 is the backup product known once again as CrashPlan, and version 11 is the Code42 security product, Incydr. Per the team in #crashplan in the MacAdmins Slack, in early 2023, their version of the app will be renamed and rebranded as "CrashPlan". It's probably safe to assume the signing identity will change at that point, too.

For CrashPlan, the latest app can be found here for both "enterprise" and "small business" versions:

```
https://download.crashplan.com/installs/agent/latest-mac.dmg
https://download.crashplan.com/installs/agent/latest-smb-mac.dmg
```

Both installers are universal. Also, there isn't currently a "latest" download URL for Code42's Incydr (Code42 app v11). That said, Incydr customers can still manually download the installer from the Code42 admin console and use the `-p` option alongside the .munki AutoPkg recipe.

Would it make sense to rework the old "CrashPlan" recipes for these new URLs and retire the others? Then, when there's a "latest" URL for the Code42 app, the existing Code42 recipes could be updated for that, too (though maybe the recipe identifier should be changed, so admins have to deliberately pick which recipe they need).

I can work on this and submit some pull requests if that'd help!

**Comment by paul-cossey** [comment]
Thanks for the heads up, @flammable looking to revive the old recipes now.

**Comment by paul-cossey** [comment]
I've updated the CrashPlan recipes, @flammable could you give them a try and let me know if they work for you?

https://github.com/autopkg/dataJAR-recipes/tree/master/CrashPlan
https://github.com/autopkg/dataJAR-recipes/tree/master/CrashPlan%20for%20Small%20Business

**Comment by flammable** [comment]
They both work great! Thanks, Paul!

**Comment by paul-cossey** [comment]
The Code42 recipes have now been deprecated.
