### ISSUE TITLE
Acrobat DC

### ISSUE THREAD

**Issue by adrienlabigne** [autopkg/dataJAR-recipes#229]
Hello,

I am unable to import Acrobat Pro DC (APRO) 22.0 to my Munki repo with the Adobe Admin Console Packages recipe.
I have my AdobeAcrobatDC folder in ~/Downloads, I run ./AdobeAdminConsolePackagesImporter.py and the script creates the dmg, adds them to my Munki repo, but the script blocks on one step (attachment).
I let it run for several hours, but it doesn't work anymore, and never creates the pkginfo.
I managed to add all the other packages, so my method works.

Do I need to make a modification to the recipe for Acrobat?

Thanks in advance 

<img width="763" alt="image" src="https://user-images.githubusercontent.com/36637240/177181492-71c58008-ab2c-4f04-972e-c79789c9a524.png">

**Comment by paul-cossey** [comment]
Hi, @adrienlabigne 

Are you still seeing this issue?

**Comment by paul-cossey** [comment]
It's working for us, I imported Acrobat DC just the other day. 

Are you using the latest version of `AdobeAdminConsolePackagesImporter.py`? And what version of Autopkg are you running?

**Comment by adrienlabigne** [comment]
Arf…

Yes, I pull all DataJAR repo on my computer and paste the new files, and same error.
Autopkg 2.7

I'll try on my other computer for this package.

**Comment by adrienlabigne** [comment]
Same error on my second computer (Macbook Pro M1 Pro). I'll try to import manually the packages to see

**Comment by adrienlabigne** [comment]
Hi, I successfully import manually this 2 dmg created with the script.
If you want take control of my computer one time to see, or some logs, tell me, If I can help ;)
