### ISSUE TITLE
warnings from renpy 8.download.recipe

### ISSUE THREAD

**Issue by workflowsguy** [autopkg/dataJAR-recipes#231]
Since a few days, for every Autopkg recipe I execute,  

`WARNING: plist error for /Volumes/Web/Softwareverteilung/Recipe-Repositories/com.github.autopkg.dataJAR-recipes/renpy 8/renpy 8.download.recipe: Invalid file`

keeps getting output repeatedly (8-10 times).

**Comment by homebysix** [comment]
@workflowsguy Could you provide the output of this command?

```
git -C /Volumes/Web/Softwareverteilung/Recipe-Repositories/com.github.autopkg.dataJAR-recipes status
```

Checking to see whether your local version is different than the latest master branch on GitHub.

**Comment by workflowsguy** [comment]
The output is this:
```
On branch master
Your branch is behind 'origin/master' by 17 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   renpy 6/renpy 6.download.recipe
	modified:   renpy 7/renpy 7.download.recipe

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Local/
	renpy 8/


It took 6.54 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by homebysix** [comment]
As suspected, it looks like there are some changes in that repo that don't align with what's on GitHub. It's not a good idea to modify the contents of recipe repos directly, as it will prevent `autopkg repo-update` and `autopkg update-trust-info` from working as expected. If these changes were unintentional, I would suggest running `repo-delete` and then `repo-add` on the dataJAR-recipes repo to sync with the latest version on GitHub. You may have to update your override trust information after doing this.

**Comment by workflowsguy** [comment]
Well, this is weird.

I am, of course, well aware that modifications to recipes are done by way of overrides (have already done quite a few of them) and not by directly modifying their source.
Also, I don't even know what program "renpy" is so had no reason to edit it's recipe files.
And nobody except me has access to the server where the munki repository is stored.

So, I can only suspect that there was some issue with `autopkg repo-update all` and/or `git`.
(Actually, running `autopkg repo-update all` complains about local changes in recipes of apps I have never used for several other repositories.)

Anyway, thank you for looking into this.
