### ISSUE TITLE
Perimeter 81 Downloading Older Version

### ISSUE THREAD

**Issue by TSPARR** [autopkg/dataJAR-recipes#243]
Looks like the Perimeter 81 recipe is downloading a fairly old version of the app. The latest is available here: [PKG](https://static.perimeter81.com/agents/mac/Perimeter81_8.0.5.143.pkg)

That came from scraping this page: https://support.perimeter81.com/v1/docs/downloading-the-agent

Could try opening a ticket with them to update their static link or maybe just move to scraping the page?

**Comment by paul-cossey** [comment]
Thanks for the heads up, @TSPARR 

This commit: https://github.com/autopkg/dataJAR-recipes/commit/29dd88e0309e939b550e36e2505ce09babc68629 should now download the latest version. Can you give it a test and let me know if it works for you please?

Thanks
Paul

**Comment by TSPARR** [comment]
Looks great! Appreciate the quick addressing of this!
 Name         Version  Catalogs  Pkginfo Path                         Pkg Repo Path                      Icon Repo Path  
    ----         -------  --------  ------------                         -------------                      --------------  
    Perimeter81  8.0.5    testing   Perimeter81/Perimeter81-8.0.5.plist  Perimeter81/Perimeter81-8.0.5.pkg
