### ISSUE TITLE
QLab Recipes

### ISSUE THREAD

**Issue by vmiller** [autopkg/dataJAR-recipes#245]
I see that QLab released version 5 August 30.  The current QLab4 recipes do not pick up the latest QLab as the update URL has changed to https://figure53.com/qlab/downloads/appcast-v5

Not sure of the best course of action : 
- create a set of QLab5 recipes
- create "versionless" recipes with an overridable download URL

Either path would require some work on the part of the users of the recipes.

**Comment by paul-cossey** [comment]
Hi, @vmiller 

Thanks for the heads up, I've just committed some QLab5 recipes: https://github.com/autopkg/dataJAR-recipes/commit/e46728adf9ec377c0d4d34f5f580cdf8e959a962 

I've gone with separate recipes due to licensing and a different signing certificate. 

Paul
