### ISSUE TITLE
Fix Python error due to out-of-date MunkiPkginfoReceiptsEditor processor

### ISSUE THREAD

**Issue by mtconleyuk** [autopkg/dataJAR-recipes#246]
Need to replace processor com.github.keeleysam.recipes.GoogleTalkPlugin/MunkiPkginfoReceiptsEditor with new core processor MunkiOptionalReceiptEditor to avoid error due to change to Python 3.10:-

        <dict>
            <key>Processor</key>
            <string>MunkiOptionalReceiptEditor</string>
        </dict>

**Comment by macmule** [comment]
linked to https://github.com/autopkg/dataJAR-recipes/pull/242/files

closing off
