### ISSUE TITLE
Figma only Apple Silicon

### ISSUE THREAD

**Issue by franton** [autopkg/dataJAR-recipes#248]
Hi,

Figma for reasons best known to themselves provides a separate download for Intel app bundle and Apple Silicon app bundle. It's not universal. Sadly the recipe is only downloading and packaging the Apple Silicon version.

Any way to get a totally universal installer?

**Comment by paul-cossey** [comment]
Hi, @franton 

Sorry, seems the reply I wrote the other day don't save, I must've closed the page!

As far as I know, there is no universal app. But the Figma download recipe has support for an architecture variable baked in already. You could create a new override for the Intel version or update your existing one.

https://github.com/autopkg/dataJAR-recipes/blob/bc198efa5ef63ee88d877f0931b69f775e85e4c6/Figma/Figma.download.recipe#L5-L18

**Comment by smithjw** [comment]
@franton Not to recipe-snipe here but I've recently updated my Figma recipes to download both installers and bake them into the same pkg. The appropriate one is installed when run on the device https://github.com/autopkg/smithjw-recipes/blob/master/Figma/Figma-Universal.pkg.recipe.yaml

**Comment by franton** [comment]
@smithjw Excellent. Recipe snipe away! (and saves me having to make one myself)
