### ISSUE TITLE
Audinate Dante Virtual Soundcard does not download latest version

### ISSUE THREAD

**Issue by mikeknight85** [autopkg/dataJAR-recipes#260]
It does not download the latest version for Apple Silicon (v4.2.4.1), only the Intel versions, because in the xml file they do not list the Apple Silicon version of the application

**Comment by macmule** [comment]
@mikeknight85 can you advise where the correct version is listed?

**Comment by mikeknight85** [comment]
https://my.audinate.com/support/downloads/dante-virtual-soundcard

**Comment by paul-cossey** [comment]
Hi, @mikeknight85 

I've just had a quick look at this, and I've found the Sparkle Feed for the arm64 version.

https://software-updates.audinate.com/DanteVirtualSoundcard/appcast/macOS/DanteVirtualSoundcard-macOS.xml

You could create a new override and use that with the `SPARKLE_FEED_URL` variable.

```
<key>SPARKLE_FEED_URL</key>
<string>https://software-updates.audinate.com/DanteVirtualSoundcard/appcast/macOS/DanteVirtualSoundcard-macOS.xml</string>
```

Let me know if that solves the issue for you, and I'll update the descriptions with this info. 

Thanks!

**Comment by mikeknight85** [comment]
Hi @paul-cossey 

Thanks, i was not able to find that feed, seems to be working for me ! Thanks a lot !

**Comment by paul-cossey** [comment]
Awesome, thanks for letting me know, and glad it worked for you @mikeknight85 

I'll update the description Monday.

**Comment by paul-cossey** [comment]
Description has been updated with the Sparkle Feeds for Apple Silicone and Intel versions.

https://github.com/autopkg/dataJAR-recipes/commit/158abda2e391552933d5a595e3a031bda45dc176
