### ISSUE TITLE
Submitting VMware Fusion 13 download recipe

### ISSUE THREAD

**Issue by rtrouton** [autopkg/dataJAR-recipes#264]
I noticed you all didn't have recipes for VMware Fusion 13 posted as of yet, so I decided to take your VMware Fusion 12 download recipe and update it for VMware Fusion 13. This seems to work, hope it helps you all out.

https://gist.github.com/rtrouton/1afdf2027f0e983cde0ed5cfc300cf3f

**Comment by paul-cossey** [comment]
Thanks, @rtrouton 

We've not had a request come in for it as yet. 

Can you give these a try? https://github.com/autopkg/dataJAR-recipes/tree/master/VMware%20Fusion%2013

**Comment by rtrouton** [comment]
Apologies for not responding in a timely manner. I've tested the `com.github.dataJAR-recipes.pkg.VMware Fusion 13` recipe and it works fine, which in turn means the download recipe is also working fine. No issues seen and I got a working VMware Fusion installer out of it.

**Comment by paul-cossey** [comment]
Thanks, Rich! 

Appreciated :-)
