### ISSUE TITLE
Stream Deck.munki.recipe has bug; name in v6 is "Elgato Stream Deck.app" and not "Stream Deck.app"

### ISSUE THREAD

**Issue by fseesink** [autopkg/dataJAR-recipes#270]
Been having an issue where if I install Stream Deck via this Munki recipe, with each run of Managed Software Update, it claims a new version exists, even though what it wants to install/update is the same 6.0.3 that's already installed.  I had this issue previously, to the point I just uninstalled Stream Deck as far as Munki was concerned and then installed it separately.  So then Munki ignored it.

But with the recent update, I circled back to this and decided to get to the bottom of this.  And I found the root cause.  In `Stream Deck.munki.recipe` starting on line 64 where the Versioner processor is configured:
```xml
        <dict>
            <key>Processor</key>
            <string>Versioner</string>
            <key>Arguments</key>
            <dict>
                <key>input_plist_path</key>
                <string>%destination_path%Applications/Stream Deck.app/Contents/Info.plist</string>
            </dict>
        </dict>

```
the name of the application is wrong.  It is not `Stream Deck.app` but rather `Elgato Stream Deck.app`.  This is why when I ran
```shell
sudo managedsoftwareupdate -vvv
```
in the output I saw the following:
```
...
    * Processing manifest item StreamDeck for update
    Looking for detail for: StreamDeck, version latest...
    Considering 1 items with name StreamDeck from catalog production
    Considering item StreamDeck, version 6.0.3 with minimum os version required 10.15
    Our OS version is 13.2
    Found StreamDeck, version 6.0.3 in catalog production
    /Applications/Stream Deck.app/Contents/Info.plist doesn't exist.
    StreamDeck does not appear to be installed, so no managed updates...
...
```
Note the 2nd to last line.  It's trying to find the version info in an Info.plist file that doesn't exist, because the path to that file is wrong since the name of the app listed is incorrect.  I believe this is what triggers Managed Software Center to try to install/upgrade the s/w over and over again.

To be clear, it looks like the application changed names with the release of v6.  I pulled down the last v5 release and noticed that it was set to install the app as "Stream Deck.app".

**Comment by paul-cossey** [comment]
Hi, @fseesink 

Thanks for raising this. 

I've had a quick look, I would have expected the recipe to fail to generate the Installs Array if the name of the app is incorrect, but it doesn't, it creates the Installs Array as expected, if you inspect the package with Suspicious Package you can see it's called `Stream Deck.app`. 

<img width="776" alt="Screenshot 2023-02-13 at 14 37 22" src="https://user-images.githubusercontent.com/16046272/218487172-66044a08-8b6d-4924-803a-51adce024882.png">

So, I dug a bit further and the issue is with the pkg's `postinstall` script. For _reasons_ it renames `Stream Deck.app` to `Elgato Stream Deck.app`

```
#!/bin/bash

# finalize Stream Deck installation, update permissions and owner

APP_INSTALLED="/Applications/Stream Deck.app"
APP_RENAMED="/Applications/Elgato Stream Deck.app"

if [ -d "${APP_INSTALLED}" ]; then
	# I wanna be a root
	chown -R root:wheel "${APP_INSTALLED}"
	chmod -R 755 "${APP_INSTALLED}"

	rm -rf "${APP_RENAMED}"
	mv "${APP_INSTALLED}" "${APP_RENAMED}"
```

I should be able to do something to generate an Installs Array for Elgato Stream Deck.app instead.

**Comment by paul-cossey** [comment]
Hi, @fseesink 

I've just created some new recipes for Elgato Stream Deck, the Munki recipe should create the correct installs array now. 

https://github.com/autopkg/dataJAR-recipes/tree/master/Elgato%20Stream%20Deck 

Could you give them a try for me please, and let me know if it resolves the issue for you? 

Thanks!

**Comment by fseesink** [comment]
Hey @paul-cossey ,

Sorry for slow response. I just got around to trying that, and I believe it's working now.  Took me a few to realize I had to remove the old recipe override and start fresh.  But yes, it doesn't do the constant download anymore.  The real test will come with the next update (I'm on 6.0.5 right now).  But suspect all's good now.

**Comment by paul-cossey** [comment]
Great, thanks for confirming, @fseesink 😄
