### ISSUE TITLE
MBBR Download Issues

### ISSUE THREAD

**Issue by joncrain** [autopkg/dataJAR-recipes#272]
MBBR switched to downloading the package instead of a zip file. The PackageInfo file also contains a peg-info version of 1.0 so a simple update to the download file name and removing the zip processing still does not pull the correct version.

**Comment by paul-cossey** [comment]
Hi, @joncrain 

Thanks for raising this, as mentioned in the Mac Admins Slack we no longer use these recipes, but I've given them an overhaul, by adding the creation of an Installs Array, an uninstall script, and it now sets the `minimum_os_version` from the Engine.bundle's info.plist. 

If you're happy with this https://github.com/autopkg/dataJAR-recipes/commit/f5de2f6f818bd01fd7868501b74114a032f7b767 commit? I'll close this off. 😄
