### ISSUE TITLE
Krisp Download URL no longer works

### ISSUE THREAD

**Issue by mdb-scottb** [autopkg/dataJAR-recipes#281]
The Krisp recipe returns the following error:
```
Krisp.munki.recipe
Error in local.munki.Krisp: Processor: URLDownloader: Error: curl: (22) The requested URL returned error: 400
```
The download URL https://api.krisp.ai/v2/download/mac?btn=downloadMac_AccountFooter returns the full error

**Comment by macmule** [comment]
thanks @mdb-scottb, also @arubdesu mentioned this on Slack.

Changing the download URL to [https://api.krisp.ai/v2/download/mac](https://api.krisp.ai/v2/download/mac) works to download.. but then pulling apart the pkg is problematic

**Comment by macmule** [comment]
I've updated the recipes.. should be all good now.. thanks @mdb-scottb and @arubdesu
