### ISSUE TITLE
nodejslts.download.recipe no URL matches

### ISSUE THREAD

**Issue by opus-nbo** [autopkg/dataJAR-recipes#293]
@red5coder Your recipe does not work at the moment. The problem seems to be that the URLTextSearcher does not find the version number. As URLTextSearcher uses curl, i think it has something to do with the curl command. 

Testing with `curl https://nodejs.org/en/download/` shows that there is a 301 redirect to `https://nodejs.org/en/download` (without the `/` at the end). The command `curl https://nodejs.org/en/download`or `curl -L https://nodejs.org/en/download/` (`-L` for following redirects) did output a page, but with all the download links missing.

I don't know what is happening there. It could be some kind of protection mechanism. Maybe you get to the bottom of this.

**Comment by paul-cossey** [comment]
Hi, @opus-nbo 

I could replicate the issues you saw, but couldn't find a fix. Thankfully it it looks like it's now working again - so I'm going to challk it up to being an issue with the vendors website.

**Comment by opus-nbo** [comment]
@paul-cossey yes, you are right. it works again now. thanks for checking anyways.
