### ISSUE TITLE
Elgato Stream Deck.munki.recipe - Issue regarding FileMover processor

### ISSUE THREAD

**Issue by rquigley-aus** [autopkg/dataJAR-recipes#294]
Hi Team,

Looks like there is an issue regarding the FileMover processor part of the munki recipe for Elgato Stream Deck. The error provided is that the Directory isn't empty and therefore the file cannot be moved.

Here is a sanitized version of this output:

```
FileMover
{'Input': {'source': '/Users/$USER/Library/AutoPkg/Cache/local.munki.ElgatoStreamDeck/installer_payload/Applications/Stream '
                     'Deck.app',
           'target': '/Users/$USER/Library/AutoPkg/Cache/local.munki.ElgatoStreamDeck/installer_payload/Applications/Elgato '
                     'Stream Deck.app'}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Library/AutoPkg/autopkglib/FileMover.py", line 39, in main
    rename(self.env["source"], self.env["target"])
OSError: [Errno 66] Directory not empty: '/Users/$USER/Library/AutoPkg/Cache/local.munki.ElgatoStreamDeck/installer_payload/Applications/Stream Deck.app' -> '/Users/$USER/Library/AutoPkg/Cache/local.munki.ElgatoStreamDeck/installer_payload/Applications/Elgato Stream Deck.app'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
[Errno 66] Directory not empty: '/Users/$USER/Library/AutoPkg/Cache/local.munki.ElgatoStreamDeck/installer_payload/Applications/Stream Deck.app' -> '/Users/$USER/Library/AutoPkg/Cache/local.munki.ElgatoStreamDeck/installer_payload/Applications/Elgato Stream Deck.app'
Failed.

The following recipes failed:
    ElgatoStreamDeck.munki
        Error in local.munki.ElgatoStreamDeck: Processor: FileMover: Error: [Errno 66] Directory not empty: '/Users/$USER/Library/AutoPkg/Cache/local.munki.ElgatoStreamDeck/installer_payload/Applications/Stream Deck.app' -> '/Users/$USER/Library/AutoPkg/Cache/local.munki.ElgatoStreamDeck/installer_payload/Applications/Elgato Stream Deck.app'
```

**Comment by paul-cossey** [comment]
Hi, @rquigley-aus 

Can I ask what version of AutoPkg you're running?

I'm unable to replicate this issue

**Comment by rquigley-aus** [comment]
Hi @paul-cossey,

We're running AutoPkg 2.7.2, also deleted the RecipeOverride and re-created just in case, the only change made was changing the catalogue from testing to production and the issue is still reoccurring.

Happy to provide an unfiltered log privately if it may be of assistance.

**Comment by paul-cossey** [comment]
Thanks, @rquigley-aus 

Yes please can you send it paul@datajar.co.uk? Or you can DM on the macadmins slack @paul_cossey

**Comment by rquigley-aus** [comment]
Thanks @paul-cossey, popped the details through via a DM on the MacAdmins Slack.

**Comment by rquigley-aus** [comment]
Turns out it was an issue with the cache stored on our instance, deleting and re-running sorted the issue out. Thanks for your troubleshooting!

**Comment by saschafoerster** [comment]
Hi there, I have the same issue, but I am not able to solve it. I tried recreating the flow and deleting the cache. @rquigley-aus What did help in the end? :) 

`local.munki.Elgato Stream Deck 2	

Error in local.munki.Elgato Stream Deck 2: Processor: FileMover: Error: [Errno 66] Directory not empty: '/Users/sf/Library/AutoPkg/Cache/local.munki.Elgato Stream Deck 2/installer_payload/Applications/Stream Deck.app' -> '/Users/sf/Library/AutoPkg/Cache/local.munki.Elgato Stream Deck 2/installer_payload/Applications/Elgato Stream Deck.app'`

**Comment by rquigley-aus** [comment]
It still happens every so often, I just delete the folder and it runs again.

Probably does need to be wiped as part of the recipe.
