### ISSUE TITLE
SUPPORTED_ARCH variable is not defined in com.github.dataJAR-recipes.download.postman

### ISSUE THREAD

**Issue by rtrouton** [autopkg/dataJAR-recipes#297]
There was a recent PR to the following recipe:

`com.github.dataJAR-recipes.download.postman`
https://github.com/autopkg/dataJAR-recipes/blob/master/Postman/Postman.download.recipe

It looks like the updated version left the `.download` recipe in question with an undefined `SUPPORTED_ARCH` variable when the recipe is run by itself:

https://github.com/autopkg/dataJAR-recipes/blob/master/Postman/Postman.download.recipe#L30

**Comment by paul-cossey** [comment]
Thanks, @rtrouton 

Should be resolved with https://github.com/autopkg/dataJAR-recipes/commit/97d1790acdd47aa96895df8b984cb7f637d8ec9c
