### ISSUE TITLE
SketchUpPro2023 PKG Recipe - No Match Found

### ISSUE THREAD

**Issue by kclose3** [autopkg/dataJAR-recipes#304]
Error when trying to download SketchUpPro2023

URLTextSearcher: Error: No match found on URL: https://help.sketchup.com/en/downloading-sketchup

**Comment by paul-cossey** [comment]
Hi, @kclose3 

We're seeing this too but intermittently. 

I  _think_ there is some kind of scraping protecting on the website. Usually a re-run later in the day resolves the issues. Unfortunately I'm yet to find a more permeant fix.

**Comment by kclose3** [comment]
> Hi, @kclose3
> 
> We're seeing this too but intermittently.
> 
> I _think_ there is some kind of scraping protecting on the website. Usually a re-run later in the day resolves the issues. Unfortunately I'm yet to find a more permanent fix.

We've had very limited success... in that I think it's succeeded only once or twice, but no nearly as consistent as it sounds like you're seeing.

**Comment by paul-cossey** [comment]
Maybe as we only schedule the recipe to run once a week? I'll continue to look for a more stable way to download

**Comment by kclose3** [comment]
I'll keep an eye on it and see if there appears to be a pattern of success vs. failure.

**Comment by kclose3** [comment]
We saw it again last week, but as you mentioned, it ran fine the next day.
