### ISSUE TITLE
pgAdmin4 recipe downloads only arm64 version

### ISSUE THREAD

**Issue by d-burgess** [autopkg/dataJAR-recipes#306]
Since 7.7 postgresql.org are providing both an arm64 and an x86_64 build of pgAdmin. The recipe uses the first link on that page, so it only packages the arm64 build. As the recipe does not set the app's architecture either, this is then made available to x86_64 clients breaking the app for them.

**Comment by paul-cossey** [comment]
Hi, @d-burgess 

Thanks for raising this. Should be sorted with this https://github.com/autopkg/dataJAR-recipes/commit/972ea470e3c5d45f7efaea0cd8de58f1af67bf92 commit. Could you give it a try and let me know if that resolves this for you please?

Thanks!

**Comment by d-burgess** [comment]
This all works for me now, thanks for the fix @paul-cossey

**Comment by paul-cossey** [comment]
Awesome! Thanks for confirming @d-burgess
