### ISSUE TITLE
UPDD Commander - Error: No match found on URL: https://www.legamaster.com/downloads/software

### ISSUE THREAD

**Issue by macmule** [autopkg/dataJAR-recipes#313]
There's an issue with the site itself:

<img width="1514" alt="Screenshot 2023-12-21 at 10 42 52" src="https://github.com/autopkg/dataJAR-recipes/assets/2464974/0b7a3751-1212-4444-a733-75976994322d">

**Comment by paul-cossey** [comment]
The vendors has resolved their issues and the recipes now run without error. Closing!
