### ISSUE TITLE
AdobeAdminConsolePackagesPkgInfoCreator does not handle Acrobat DC v24.1 correctly

### ISSUE THREAD

**Issue by jazzace** [autopkg/dataJAR-recipes#322]
The file `AdobeAutoPkgApplicationData.json`, which assists the `AdobeAdminConsolePackagesPkgInfoCreator` processor when determining the package version of an Adobe Admin Console Package, was updated today to support Acrobat DC version 24. Running the `AdobeAdminConsolePackagesPkgInfoCreator` processor on an Admin Console package of Acrobat DC 24.001.20604 calculates the `aacp_application_major_version` to be 24.1 (rather than 24.0), so any recipe with that combination fails. For example, when running an override of the recipe `AdobeAdminConsole.pkg.recipe` from the `jazzace-recipes` repo that specifies the Acrobat package path:
```
com.github.dataJAR-recipes.munki.Adobe Lightroom Classic/AdobeAdminConsolePackagesPkgInfoCreator
{'Input': {'aacp_package_name': 'UC_SDL_AcrobatDCv24'}}
AdobeAdminConsolePackagesPkgInfoCreator: Starting versioner process...
AdobeAdminConsolePackagesPkgInfoCreator: aacp_package_name: UC_SDL_AcrobatDCv24
AdobeAdminConsolePackagesPkgInfoCreator: aacp_packages_path: /Users/autopkguser/Downloads/
AdobeAdminConsolePackagesPkgInfoCreator: aacp_install_pkg_path: /Users/autopkguser/Downloads/UC_SDL_AcrobatDCv24/Build/UC_SDL_AcrobatDCv24_Install.pkg
AdobeAdminConsolePackagesPkgInfoCreator: aacp_uninstall_pkg_path /Users/autopkguser/Downloads/UC_SDL_AcrobatDCv24/Build/UC_SDL_AcrobatDCv24_Uninstall.pkg
AdobeAdminConsolePackagesPkgInfoCreator: aacp_option_xml_path: /Users/autopkguser/Downloads/UC_SDL_AcrobatDCv24/Build/UC_SDL_AcrobatDCv24_Install.pkg/Contents/Resources/optionXML.xml
AdobeAdminConsolePackagesPkgInfoCreator: Processing: /Users/autopkguser/Downloads/UC_SDL_AcrobatDCv24/Build/UC_SDL_AcrobatDCv24_Install.pkg/Contents/Resources/optionXML.xml...
AdobeAdminConsolePackagesPkgInfoCreator: aacp_application_sap_code: APRO
AdobeAdminConsolePackagesPkgInfoCreator: aacp_target_folder: APRO24.1
AdobeAdminConsolePackagesPkgInfoCreator: aacp_application_architecture_type: macuniversal
AdobeAdminConsolePackagesPkgInfoCreator: aacp_application_install_lang: en_US
AdobeAdminConsolePackagesPkgInfoCreator: aacp_application_major_version: 24.1
AdobeAdminConsolePackagesPkgInfoCreator: Processing Acrobat installer
AdobeAdminConsolePackagesPkgInfoCreator: aacp_proxy_xml_path: /Users/autopkguser/Downloads/UC_SDL_AcrobatDCv24/Build/UC_SDL_AcrobatDCv24_Install.pkg/Contents/Resources/Setup/APRO24.1/proxy.xml
AdobeAdminConsolePackagesPkgInfoCreator: version: 24.001.20604
AdobeAdminConsolePackagesPkgInfoCreator: aacp_parent_dir: /Volumes/AutoPkgLibrary/AutoPkg/RecipeOverrides
AdobeAdminConsolePackagesPkgInfoCreator: aacp_json_path: /Volumes/AutoPkgLibrary/AutoPkg/RecipeOverrides/AdobeAutoPkgApplicationData.json
AdobeAdminConsolePackagesPkgInfoCreator: Processing /Volumes/AutoPkgLibrary/AutoPkg/RecipeOverrides/AdobeAutoPkgApplicationData.json...
Cannot find details for APRO with version: 24.1, in /Volumes/AutoPkgLibrary/AutoPkg/RecipeOverrides/AdobeAutoPkgApplicationData.json...
Failed.
[...]
```

(In order for my recipe to find the JSON file, I need to symlink to it in the RecipeOverrides folder. This should not be the cause of the problem, since it works with all other Adobe applications including Acrobat v.23.)

The expected run result is that the processor determines that the major version is 24.0 (which is included in the updated JSON file) rather than 24.1.

**Comment by macmule** [comment]
Thanks @jazzace, @paul-cossey brought this to my attention earlier and I'll be looking into this more tonight/tomorrow.

Updates to follow.

**Comment by macmule** [comment]
@jazzace should be done.. just needed to add 24.1 to the json - https://github.com/autopkg/dataJAR-recipes/commit/06ee1c4d9c5989b83703cf8c96443c883c484350

Test and let me know.

**Comment by jazzace** [comment]
This works. Thanks for the quick fix (and working around Adobe being Adobe).
