### ISSUE TITLE
Arm64 Version for IntelliJ IDEA CE?

### ISSUE THREAD

**Issue by James-von-Detroit** [autopkg/dataJAR-recipes#323]
Is there a way to make the recipe universal? where the PKG it creates has both versions? Or even give the option for Arm64 in the overrides? 

For https://github.com/autopkg/dataJAR-recipes/blob/master/IntelliJ-IDEA-CE/IntelliJ-IDEA-CE.download.recipef

**Comment by macmule** [comment]
Hi @James-von-Detroit, we'll not have a single package.. but can have a look to see if we can offer a way to download different architectures.

**Comment by macmule** [comment]
Actually.. this might not be that simple.. the .download relies on a custom processor (https://github.com/autopkg/mosen-recipes/blob/master/JetBrains/JetbrainsURLProvider.py), and it's that that needs updating.

**Comment by James-von-Detroit** [comment]
Even just that would be helpful. Then i could do an override and then have
a separate stream.

Thanks for the help!

**Comment by James-von-Detroit** [comment]
One commend is, i downloaded 2023.1.2 a few months ago with the same process with AutoPKG. That package actually came out as a universal package and worked for both Intel and Arm. But these new packages dont, it's Intel only. If you install it on an Arm, then it will fail.

**Comment by paul-cossey** [comment]
Hi, @James-von-Detroit 

We don't actually use these recipes anymore. We use the bnpl's ones here: https://github.com/autopkg/bnpl-recipes/tree/master/JetBrains they all have architecture support. 

I'll deprecate these (actually thought it was already!)

**Comment by paul-cossey** [comment]
https://github.com/autopkg/dataJAR-recipes/compare/3e6df6e0ca75...49f03b46ac0e

**Comment by paul-cossey** [comment]
I'll close this off now, as our recipes are deprecated.
