### ISSUE TITLE
nodejslts.download.recipe not finding the latest update

### ISSUE THREAD

**Issue by arekdist** [autopkg/dataJAR-recipes#325]
I'm not sure what is going on with nodejslts.download.recipe but looking at the url of `https://nodejs.org/en/blog` with serch pattern eg.:
```
curl -s https://nodejs.org/en/blog | egrep -o "Node v([0-9]+(\.[0-9]+)+) \(LTS\)"
Node v18.20.1 (LTS)
Node v18.20.1 (LTS)
Node v18.20.1 (LTS)
Node v20.12.1 (LTS)
Node v20.12.1 (LTS)
Node v20.12.1 (LTS)
Node v20.12.0 (LTS)
Node v20.12.0 (LTS)
Node v20.12.0 (LTS)
Node v18.20.1 (LTS)
Node v18.20.1 (LTS)
Node v18.20.1 (LTS)
Node v20.12.1 (LTS)
Node v20.12.1 (LTS)
Node v20.12.1 (LTS)
Node v20.12.0 (LTS)
Node v20.12.0 (LTS)
Node v20.12.0 (LTS)
```
it looks as maintainer doesn't care about the correct order of updates and this source is probably not reliable.
The effect of this is that currently autopkg imports version 18.20.1 as the "newest".

**Comment by juloski** [comment]
Comment for issue observation :)

**Comment by paul-cossey** [comment]
Thanks for raising this, 

Looking at https://nodejs.org/en/blog/release it seems `18.20.1` _is_ the latest or at least it just so happens to have been the version most recently updated. 
<img width="1040" alt="Screenshot 2024-04-05 at 09 59 39" src="https://github.com/autopkg/dataJAR-recipes/assets/16046272/ef1d2cb1-9f57-40b6-b489-6af7fd0c8494">

**Comment by paul-cossey** [comment]
We could use this https://nodejs.org/dist/ and have major version as a variable?

**Comment by arekdist** [comment]
> We could use this https://nodejs.org/dist/ and have major version as a variable?

Good idea!

**Comment by paul-cossey** [comment]
I might have time to get to it this afternoon, but if anyone has any immidiate capacity we accept PR's 😄

**Comment by paul-cossey** [comment]
Ok, updated the recipes. Could you give https://github.com/autopkg/dataJAR-recipes/commit/86473ce4328905818541cab0ffdcedb631e2aedb a try please? 

I've tested with major versions 21, 20, 18 and seems ok here.

**Comment by arekdist** [comment]
Checked and works as expected. Thanks!

**Comment by paul-cossey** [comment]
Great, I'll close this off. Thanks for raising, @arekdist
