### ISSUE TITLE
Sketchup 2024 EN download no matchup found

### ISSUE THREAD

**Issue by precursorca** [autopkg/dataJAR-recipes#329]
When running the Sketchup 2024 EN download recipe:
"No match found on URL: https://help.sketchup.com/en/downloading-sketchup"

**Comment by paul-cossey** [comment]
Hi, @precursorca 

Thanks for raising, this is a know issue we've seen from time to time with the SketchUp web site. A re-run (or two) of the recipes will _usually_  resolve it. 

Please see: https://github.com/autopkg/dataJAR-recipes/issues/304

**Comment by paul-cossey** [comment]
Could be that I need to add a referer to URLTextSearcher. I've had to do so to fix the 2023 recipes: https://github.com/autopkg/dataJAR-recipes/commit/192770d11ac30e012f1e8d8d6941066be798830c

**Comment by paul-cossey** [comment]
We've not seen this happen again for a while now. Closing.
