### ISSUE TITLE
Post Haste

### ISSUE THREAD

**Issue by macmule** [autopkg/dataJAR-recipes#33]
Sparkle Feed seems to have an invalid xml:

> <?xml version="1.0" encoding="UTF-8"?>
>         <rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" >
>         <channel>
>          <title>Post Haste for Mac Appcast</title>
>          <link>http://www.digitalrebellion.com/posthaste</link>
>          <description>Appcast for Digital Rebellion's post production software.</description>
>          <language>en</language>
>          <copyright>2015 Digital Rebellion LLC</copyright><item>
>            <title>Post Haste for Mac 2.4.2</title>
>            <pubDate>Wed, 29 Jul 2015 05:51:47 +0200</pubDate>
>            <link>http://www.digitalrebellion.com/posthaste</link>
>            <enclosure url="http://download.digitalrebellion.com/posthaste/Cut_Notes_2420.png" sparkle:version="2420" sparkle:shortVersionString="2.4.2" type="application/octet-stream" />
>            <description>&lt;ul&gt;
> &lt;li&gt;Fixed a crash that could occur when...&lt;/li&gt;
> &lt;/ul&gt;</description></item></channel></rss>

**Comment by Daz-wallace** [comment]
Looks like the Sparkle feed doesn't exist anymore as it 404's on the site.
Quick look inside the App (v2.6.4) looks like it no longer uses Sparkle?

**Comment by Daz-wallace** [comment]
Fixed in commit https://github.com/autopkg/dataJAR-recipes/commit/18605f5972a5ce82827c2b4df2953ac17ae645f1
