### ISSUE TITLE
Request for a recipe for Burp Suite Community

### ISSUE THREAD

**Issue by juloski** [autopkg/dataJAR-recipes#331]
Hello.

Could you please create a recipe for "Burp Suite Community" based on recipe "Burp Suite Professional"?

Thank you in advance.

Have a nice day.
Juliusz

**Comment by paul-cossey** [comment]
Hi, @juloski 

We don't currently have a need for the Burp Suite Community edition, and wouldn't usually write recipes for Titles we don't need, but as it was quick and simple to extend the functionality of the professional recipes, I've gone ahead and done that. 

https://github.com/autopkg/dataJAR-recipes/commit/f2f3bf3f9fd2b9423c56511a6651075721e8cdc1 

Hopefully it's of use to you. 

Thanks!

**Comment by juloski** [comment]
Thank you very much.
I will check and let you know tomorrow.

**Comment by juloski** [comment]
Works great.

Once again, thank you very much for your contribution.
