### ISSUE TITLE
MakeHuman: URLTextSearcher: Error: Command '['/usr/bin/curl', '--compressed', '--location', 'http://download.tuxfamily.org/makehuman/releases/']' returned non-zero exit status 28.

### ISSUE THREAD

**Issue by macmule** [autopkg/dataJAR-recipes#340]
Looks like this is related to an issue to an issue affecting `http://download.tuxfamily.org/`

**Comment by paul-cossey** [comment]
Vendor seems to have resolved the outage and the recipe is back running as expected. 

Closing
