### ISSUE TITLE
Nitro PDF Pro: Error in com.github.dataJAR-recipes.download.NitroPDFPro: Processor: URLDownloader: Error: curl: (22) The requested URL returned error: 404

### ISSUE THREAD

**Issue by macmule** [autopkg/dataJAR-recipes#341]
The download link under https://www.gonitro.com/mac/download for Nitro PDF Pro is pointing art 13.3.1 and not 14.2, as per - https://www.gonitro.com/product-details/release-notes/mac

Have notified the vendor.

**Comment by paul-cossey** [comment]
Resolved with this commit https://github.com/autopkg/dataJAR-recipes/compare/2792cfce4f3d...7162540db7ef 

Closing!
