### ISSUE TITLE
Ultimaker Cura 5.7.2 has -RC2 in its tag

### ISSUE THREAD

**Issue by TonyPaco** [autopkg/dataJAR-recipes#343]
Kind of a two-headed monster this morning...

First, I found that it was only getting the ARM64 version of Cura, and I _think_ I addressed that in my pull request: https://github.com/autopkg/dataJAR-recipes/pull/342

However, on the Cura github, they left the -RC2 tag for the release posting but didn't include it in the bundle id for the app, so the code signature verification fails because the app bundle is "nl.ultimaker.cura_UltiMaker_Cura_5.7.2" and not "nl.ultimaker.cura_UltiMaker_Cura_5.7.2-RC2". I don't know how to elegantly fix this, so I'm just going to use a DISABLE_CODE_SIGNATURE_VERIFICATION in my override and not send it to my clients until the dust settles.

**Comment by paul-cossey** [comment]
Thanks for the PR, @TonyPaco 

I think I've figured it out, `GitHubReleasesInfoProvider` overrides the `version` variable defined earlier in the recipe. 
```
{'Output': {'version': '5.7.1'}}
and
'version': '5.7.2-RC2'
```

I've changed the name of that from `version` to `DOWNLOAD_VERSION` and used that in `CodeSignatureVerifier`

Could you give this commit a try please? https://github.com/autopkg/dataJAR-recipes/compare/c733a76ba1d3...15f28fefff7b

**Comment by paul-cossey** [comment]
Actually, hold fire, @TonyPaco it's picking up `DOWNLOAD_VERSION': '5.7.1'` and still failing. Let me quickly try something else...

**Comment by TonyPaco** [comment]
FWIW @paul-cossey, I saw that '5.7.1' fly by in the -vvvv runs I made a few days ago, yet it still seemed to grab version 5.7.2 of the dmg. ???

**Comment by paul-cossey** [comment]
I'm now grabbing the version number from the App - this should fix our woes: https://github.com/autopkg/dataJAR-recipes/compare/15f28fefff7b...3ba12c29ecc9 

😄

**Comment by TonyPaco** [comment]
I'll give it a whirl now.

**Comment by TonyPaco** [comment]
Both my overrides are running clean without errors. Thanks @paul-cossey!

**Comment by paul-cossey** [comment]
Thanks for confirming, @TonyPaco!

I'll close this off now 😃
