### ISSUE TITLE
Current custom Adobe (non flat) console created packages fail on latest macOS Sequoia

### ISSUE THREAD

**Issue by pnerum** [autopkg/dataJAR-recipes#344]
Due to the deprecation of non flat component packages in the latest macOS Sequoia, we can't install the Adobe apps using Munki anymore.

Previous in macOS Sonoma we got an error message:
_DEPRECATION WARNING] -- Legacy Installer Package
installer: This package will be incompatible with a future version of macOS. Contact the developer for support.`_

In macOS Sequoia we get an actual installation error:
_This package is incompatible with this version of macOS. Contact the developer for support_

In the Adobe Admin console we can now create flat custom packages. I have to check if this will work with the current recipes.
I will this issue when tested.

**Comment by macmule** [comment]
thanks @pnerum, we'll need to make changes to the processor for Flat PKGs and the fact the there is no uninstall pkg for them.

**Comment by pnerum** [comment]
I just created a flat package and indeed noticed there isn't an uninstall package. I guess we need to deploy the Adobe uninstall tool and use that for uninstalling as uninstall script with Munki.

Just for the fun of it, I tried the recipe using the old component package structure and replace the component package for a flat package version. Didn't work. 

If you want me to test please let me know!

**Comment by macmule** [comment]
Forgot to say.. we've updated the recipes and they now support flat packages!

[https://github.com/autopkg/dataJAR-recipes/tree/master/Adobe%20Admin%20Console%20Packages](https://github.com/autopkg/dataJAR-recipes/tree/master/Adobe%20Admin%20Console%20Packages)

Give them a go, and reach out if any issues.
