### ISSUE TITLE
Catalyst Browse download recipe links to old 2023 Intel version

### ISSUE THREAD

**Issue by adamlazar1** [autopkg/dataJAR-recipes#351]
https://www.sony.com/electronics/support/articles/CCCT03000

Here's a link for the 2024 (Universal) version: 
https://support.d-imaging.sony.co.jp/disoft_DL/CatalystBrowse_DL/mac?fm=en

**Comment by paul-cossey** [comment]
Hi, @adamlazar1 

Thanks for raising this. I've just given the recipes a rewrite, could you give this commit https://github.com/autopkg/dataJAR-recipes/commit/03feca865ae9a9255c2e851d559626cf06a69642 at try please and let me know if that resolve this issue for you? 

Thanks
