### ISSUE TITLE
Resolume Arena cloudfront prefix

### ISSUE THREAD

**Issue by jgstew** [autopkg/dataJAR-recipes#352]
I don't know if you were the one who asked at my workshop at PSU MacAdmins 2024 about not hard coding the cloudfront url prefix for Resolume, but I did end up writing a download recipe that solves this.

Regarding: https://github.com/autopkg/dataJAR-recipes/blob/master/Resolume%20Arena/Resolume%20Arena.download.recipe

See: https://github.com/jgstew/jgstew-recipes/blob/main/Resolume/Arena-Mac.download.recipe.yaml

**Comment by paul-cossey** [comment]
Hey, @jgstew 

I don't think it was us you spoke to. What was the reasoning for not having the prefix hardcoded? AFAIK that doesn't change?

**Comment by jgstew** [comment]
I think the concern was how to handle it automatically in the case where it would change periodically, but yes I don't think you were who I spoke to, but I searched and found this recipe and wondered.

**Comment by paul-cossey** [comment]
Ah ok, gotcha - I could be _totally_ wrong, but I think the prefix is like an org identifier, so the cloudfront equivalent of `datajar.cloudfront.net` for example.

**Comment by paul-cossey** [comment]
I'll close this off as it's not us that you spoke to.
