### ISSUE TITLE
 URLTextSearcher: Error: No match found on URL Isador Munki recipe

### ISSUE THREAD

**Issue by jaw4uz** [autopkg/dataJAR-recipes#355]
When running the Isadora 3 Munki recipe I'm getting the following error.

 Error in local.munki.Isadora3RiderOver: Processor: URLTextSearcher: Error: No match found on URL: https://troikatronix.com/get-it/

It looks like Isadora has been updated to version 4.

**Comment by paul-cossey** [comment]
Hi, @jaw4uz 

I actually fixed the Isadora3 recipes just before you posted: https://github.com/autopkg/dataJAR-recipes/compare/9720c8a91a8d...f8dd570aa3e5

I'm just testing some Isadora4 recipes, hopefully they should be live later today/tomorrow

**Comment by paul-cossey** [comment]
Isadora 4 recipes are here: https://github.com/autopkg/dataJAR-recipes/tree/master/Isadora%204 @jaw4uz
