### ISSUE TITLE
DB Browser for SQLite.download.recipe needs URL path updated (missing a "v")

### ISSUE THREAD

**Issue by fseesink** [autopkg/dataJAR-recipes#357]
Currently `DB Browser for SQLite.download.recipe` tries to pull down the appropriate .DMG files using
```
<string>DB\.Browser\.for\.SQLite-%DOWNLOAD_ARCH%([0-9]+(\.[0-9]+)+)\.dmg</string>
```

But it appears that with v3.13.0 released on 22 July, they changed things a little.

First, they seem to have gone to a Universal Binary (vs. the architecture-specific x64 or ARM64 builds).  If this is how they're going to do things, it may no longer be necessary to have the DOWNLOAD_ARCH and SUPPORTED_ARCH variables, simplifying the recipes.

Second, and the reason I am writing this, the filename adjusted ever so slightly by adding a "v" in front of the version.  So the current filename is
```
DB.Browser.for.SQLite-v3.13.0.dmg
```
Notice this will not match with the string above, even with DOWNLOAD_ARCH set to "", due to the missing "v" in the search string.  It should read instead
```
<string>DB\.Browser\.for\.SQLite-%DOWNLOAD_ARCH%v([0-9]+(\.[0-9]+)+)\.dmg</string>
```
if nothing else.

So currently the recipe keeps finding version 3.12.2 further down instead.

**Comment by macmule** [comment]
Thanks @fseesink.

Should have been addressed in - https://github.com/autopkg/dataJAR-recipes/commit/916692bd5b7c690823177ed9002923ced6793416, so if you update this repo you should be good :)
