### ISSUE TITLE
CodeSignatureVerifier glob error for Axure RP 10-Trial.download.recipe

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#365]
Hey folks,
Looks like Axure have released v11 so the direct download link now pulls down v11 and fails the glob. 
Gonna look at a PR to fix the v10 recipe and leave it for you to create a new v11 recipe :) 

PR incoming shortly!
D

**Comment by Daz-wallace** [comment]
PR in, feel free to tweak as you want.
**NOTE:**
- URL input has been removed
- ARCHITECTURE inout has been added. Set ARCHITECTURE to "-arm64" to download for Apple Silicon. Leave blank for Intel.

**Comment by paul-cossey** [comment]
Thanks for the heads up and PR, @Daz-wallace 

I've knocked up some V11 recipes - just need to test before I commit them. Should be up tomorrow I'd think.

**Comment by paul-cossey** [comment]
Andddd recipes added for AxureRP11: https://github.com/jamf/private-recipes/compare/3bbd7ae9f1ed...0174a9efeecd
