### ISSUE TITLE
stuck at BlockBlock 2.2.2

### ISSUE THREAD

**Issue by mallej** [autopkg/dataJAR-recipes#367]
Hi, any idea why the BlockBlock recipe is not downloading the last version 2.2.4 ? It downloads 2.2.2.
I checked the URL for 2.2.4 and its there and working in Safari:
https://github.com/objective-see/BlockBlock/releases/download/v2.2.4/BlockBlock_2.2.4.zip
Could it be related to the website where it is also stuck at 2.2.2 :
https://objective-see.org/products/blockblock.html

**Comment by paul-cossey** [comment]
Hi, @mallej 

Yes it's exactly that. The download recipe searches the main website for the download url rather than GitHub. 

https://github.com/autopkg/dataJAR-recipes/blob/master/BlockBlock/BlockBlock.download.recipe#L18#L30

**Comment by paul-cossey** [comment]
The release has been out for a month - I'll have a look at switching the recipe to using the GitHub Releases page.

**Comment by paul-cossey** [comment]
I've just switched to using GitHubReleasesInfoProvider could you give this [commit](https://github.com/autopkg/dataJAR-recipes/compare/c03eda91ffea...28c3c609171c) a try please, @mallej

**Comment by paul-cossey** [comment]
This is working as expected for us I'll close this now.
