### ISSUE TITLE
Adobe Console packages and yaml munki overrides "invalid file error"

### ISSUE THREAD

**Issue by pnerum** [autopkg/dataJAR-recipes#368]
We use yaml files for all our new munki recipe overrides. It seems that version 3 of the AdobeAdminConsolePackagesImporter.py doesn't go well with those recipes. 

The last line of the output of the script is:
_ERROR: Attempting to convert the content of /Users/hradmin/Library/AutoPkg/RecipeOverrides/AdobeAnimate2024.munki.recipe.yaml to dict, failed with error error: Invalid file_

I've tried 2 different recipe overrides that got the same output error.

Here's an example of a yaml override we use. I had to put .txt at the end otherwise I couldn't upload it to GH.
[AdobeAfterEffects2024.munki.recipe.yaml.txt](https://github.com/user-attachments/files/17343834/AdobeAfterEffects2024.munki.recipe.yaml.txt)

All best,

Patrick van Nerum

**Comment by paul-cossey** [comment]
I think that'll be because the updated processor writes back variables in to the override, can you use the standard plist formats for your data overrides?

**Comment by pnerum** [comment]
Hi Paul,

I certainly can! If it's not an easy/quick fix for you or Ben I'm totally fine to re-create the recipes in plist format!

**Comment by macmule** [comment]
@paul-cossey @pnerum  they should support yaml.. just need to dig into it

**Comment by macmule** [comment]
@pnerum can you do a repo update and try again?

Was resolved in https://github.com/autopkg/dataJAR-recipes/commit/c05b89b5f55f372a69ad49a176b680b9c6a15b6e, and was a simple fix too.. just a missed copy and paste.

**Comment by pnerum** [comment]
Hey Ben,

I can confirm that my yaml adobe recipes worked like a charm! Thank you so much!

Cheers,

Patrick
