### ISSUE TITLE
Adobe Admin Console munki recipes AdobeDimension and AdobeDreamweaver2021 uninstall script errors

### ISSUE THREAD

**Issue by pnerum** [autopkg/dataJAR-recipes#374]
Hi,

First the good news: I ran all the new Adobe admin recipes and checked if they installed en uninstall correctly using Munki.
All results ran without problems. 

Only 2 packages fail to uninstal using the uninstall script with Munki:

- AdobeDimension
- AdobeDreamweaver2021

In de munki pkginfo the uninstall script contains the variables and not the exact extracted data from te variables.
It seems the autopkg recipe override and AdobeAdminConsolePackagesImporter.py aren't able to extract these needed variable results:
- aacp_application_base_version
- aacp_sap_code

I hope this makes sense?

Here are 2 examples:

Working uninstall script in the munki pkginfo.
I only post after the "# Attempt the uninstall" from the uninstall script:
`if "${uninstallerPath}" --baseVersion="3.0.0" --deleteUserPreferences="false" --platform="macOS" --sapCode="SBSTA" --uninstall="1"`

Not working uninstall script in the munki pkginfo.
I only post after the "# Attempt the uninstall" from the uninstall script:
`if "${uninstallerPath}" --baseVersion="%aacp_application_base_version%" --deleteUserPreferences="false" --platform="macOS" --sapCode="%aacp_sap_code%" --uninstall="1"`

I tried yaml and plist versions of the recipes, didn't make a difference.

I will try to manually retrieve the missing variables and will post that outcome shortly. Because maybe this information is missing from the source package installers?

Cheers,

Patrick van Nerum

**Comment by pnerum** [comment]
Manually entering the variable info for Dreamweaver worked to uninstall Dreamweaver:
`if "${uninstallerPath}" --baseVersion="21.0" --deleteUserPreferences="false" --platform="macOS" --sapCode="DRWV" --uninstall="1"`

**Comment by pnerum** [comment]
Manually entering the variable info for Dreamweaver worked to uninstall Dimension
`if "${uninstallerPath}" --baseVersion="3.0" --deleteUserPreferences="false" --platform="macOS" --sapCode="ESHR" --uninstall="1"`

**Comment by macmule** [comment]
Thanks, @pnerum.. tbh I'm not surprised that these legacy titles are being a pain.. will have a look shortly.

**Comment by macmule** [comment]
@pnerum, both titles uninstalled for me with no changes made... the below is from AdobeAdminConsolePackagesImporter.py's output:

```
Uninstalling: AdobeDimension, with: /Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Setup...
Running: ['/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Setup', '--baseVersion=3.0', '--deleteUserPreferences=false', '--platform=macOS', '--sapCode=ESHR', '--uninstall=1']
Exit Code: 0
```

```
Uninstalling: AdobeDreamweaver2021, with: /Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Setup...
Running: ['/Library/Application Support/Adobe/Adobe Desktop Common/HDBox/Setup', '--baseVersion=21.0', '--deleteUserPreferences=false', '--platform=macOS', '--sapCode=DRWV', '--uninstall=1']
Exit Code: 0 
```

So, that confirms that uninstalling via AdobeAdminConsolePackagesImporter.py works.. I'll check the uninstall script in the pkg info next

**Comment by pnerum** [comment]
Ah, so the issue is with my setup. I already created new packages and new recipes without any luck.

**Comment by macmule** [comment]
@pnerum all I did was confirm that the uninstall process works for when AdobeAdminConsolePackagesImporter.py is uninstalling.. there does seem to be an issue with the variable expansion and the uninstall script in the pkg info.. looking at that now.

**Comment by macmule** [comment]
@pnerum I found the issue.. had an old variable name in the uninstall scripts for Dimension and Dreamweaver.. have updated the recipes.. can you update the repo and confirm it's working as expected?

**Comment by pnerum** [comment]
The uninstall scripts do contain the correct information now, so I can confirm it has been resolved!

Thanks!!!

**Comment by macmule** [comment]
Awesome, thanks for raising and testing :)
