### ISSUE TITLE
FreeCAD download recipe requires update

### ISSUE THREAD

**Issue by robertryansqub** [autopkg/dataJAR-recipes#377]
The FreeCAD 1.0 release seems to have a new naming convention for the downloads, eg.

FreeCAD_1.0.0-conda-macOS-arm64-py311.dmg
FreeCAD_1.0.0-conda-macOS-x86_64-py311.dmg

The current version only picks up the 0.21 release. A trivial change would be to just append the "-py311" string but that obviously has its own future-proofing issues.

**Comment by robertryansqub** [comment]
Also, the Code Signature has changed to:

`identifier "org.freecad.FreeCAD" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = "289DJRF23X"`

**Comment by paul-cossey** [comment]
Hi, @robertryansqub 

Thanks for raising, could you give this commit https://github.com/autopkg/dataJAR-recipes/compare/e64e4a186fdf...33f6628d2ee5 at try please? Should pull down the latest version now

**Comment by robertryansqub** [comment]
Yes, that works nicely. Thanks!
