### ISSUE TITLE
AdobeAdminConsolePackagesImporter.py - ARM installer being chosen over x86 on arm64

### ISSUE THREAD

**Issue by macmule** [autopkg/dataJAR-recipes#380]
```AdobeSubstance3DPainter_en_US_MAC.pkg cannot be installed on this Mac as required a different processor architecture, looking for an installer for the same title from which we can copy the metadata from.```

**Comment by chrisgrande** [comment]
Not sure if this is related but when I have a _MAC.pkg and _MACARM.pkg it just imports the _MAC twice into Munki. I do have two overrides one with _arm64 in the name.

```
The following new items were imported into Munki:
    Name                     Version  Catalogs  Pkginfo Path                                                 Pkg Repo Path                                                        Icon Repo Path  
    ----                     -------  --------  ------------                                                 -------------                                                        --------------  
    AdobeSubstance3DPainter  10.1.2   testing   Adobe/SDL/Substance/AdobeSubstance3DPainter-10.1.2.plist     Adobe/SDL/Substance/AdobeSubstance3DPainter_en_US_MAC-10.1.2.pkg                     
    AdobeSubstance3DPainter  10.1.2   testing   Adobe/SDL/Substance/AdobeSubstance3DPainter-10.1.2__1.plist  Adobe/SDL/Substance/AdobeSubstance3DPainter_en_US_MAC-10.1.2__1.pkg                  
```

**Comment by macmule** [comment]
really bizarre.. as that issue should be fixed in 3.14.. which in our testing it seemed to.

Are you sure you’re running 3.1.4?

Can you please create an new issue, with some recipe run output?

________________________________

**Comment by chrisgrande** [comment]
False alarm — I forgot to change the identifier of my arm64 override. 🤦🏻 

All working, only thing I noticed is the arm64 pkginfo gets a __1 in the filename instead of arm64 or something similar, doesn't alter functionality, just not sure if that's intended.

**Comment by paul-cossey** [comment]
Glad it's working now. 

The _1 is a Munki thing. You can't have a file name with the same name twice so a number gets appended. It scales up the more of the same version you import _2, _3 etc... 

If you wanted the file name to include architecture types it would need to be written in to the recipe.
