### ISSUE TITLE
soapUI.download.recipe returns a 403 error

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#387]
Hey folks,

Looks like SoapUI have changed something.

The current download recipe results in a 403 error when it tries to use this URL:
https://dl.eviware.com/soapuios/5.8.0/SoapUI-5.8.0.dmg
The same URL 403's in a browser too.

Running through their download steps in a web page manually results in this URL:
https://dl.eviware.com/soapuios/5.8.0/SoapUI-x64-5.8.0.dmg

So as _a_ fix, you could change [line 37](https://github.com/autopkg/dataJAR-recipes/blob/master/SoapUI/SoapUI.download.recipe#L37) from:
`                <string>https://dl.eviware.com/soapuios/%version%/SoapUI-%version%.dmg</string>`
to
`                <string>https://dl.eviware.com/soapuios/%version%/SoapUI-x64-%version%.dmg</string>` 

However, this also works for an Apple Silicon build using the URL:
https://dl.eviware.com/soapuios/5.8.0/SoapUI-arm64-5.8.0.dmg

So I've not got a PR for you as there's a few ways you could do the multi-arch support. I'll leave that one for you :)

**Comment by paul-cossey** [comment]
Cheers, @Daz-wallace 

Can you give this a whirl? https://github.com/autopkg/dataJAR-recipes/commit/56537a7d33efc53f48ba57d2b58bb72447aaa177

**Comment by Daz-wallace** [comment]
Heya Paul,
All worked good except for the notes about the Arch for Intel. This should be "x64" not "x86_64" 
You ok to poke? :)

**Comment by paul-cossey** [comment]
The download recipe has `DOWNLOAD_ARCH` and that has x64 in the description.

The Munki and Pkg recipes have `SUPPORTED_ARCH` and they both have x86_64 in the description

The variables do different things 😄
