### ISSUE TITLE
VMware Fusion 11.5 Munki recipe problem

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/dataJAR-recipes#43]
Updated to Fusion to 11.5 via Munki on my work machine. 

1. Launched the VMware Fusion.app
2. Got prompted for admin credentials 
3. Got an error that application is damaged and is unable to start. 

Sorry I did not take a print screen. Might be worth looking into process of building the dmg image. Could be a problem there.

**Comment by macmule** [comment]
@MichalMMac Folks tested these some around the 11.5 release & advised that the post install fixes:

https://github.com/autopkg/dataJAR-recipes/blob/master/VMware%20Fusion%2011/VMware%20Fusion%2011.munki.recipe#L31

Is that in your override?

**Comment by MichalMMac** [comment]
Sorry. I must have missed that during recipe review. Thanks!
