### ISSUE TITLE
OpenJDK12 Receipe "DepricationWarning: Java version no longer publicly available"

### ISSUE THREAD

**Issue by ewtillman** [autopkg/dataJAR-recipes#46]
The OpenJDK12 Recipe is getting a error of "DepricationWarning: Java version no longer publicly available" so it no longer works.  Then the Apache netbeans recipe has a requirement of OpenJDK12, may want to update the requirement to OpenJDK13.

**Comment by macmule** [comment]
@ewtillman I wonder if we shouldn't change this to 11 or 8:

[http://netbeans.apache.org/download/nb110/nb110.html](http://netbeans.apache.org/download/nb110/nb110.html)

> Deployment platforms
Apache NetBeans 11.0 runs on JDK 8, 9, 10, 11, and 12.

**Comment by ewtillman** [comment]
@macmule ya I'm not sure what the right answer is since technically it works on multiple jdk versions. Maybe just not have a jdk set as a requirement.  I opened the ticket more so just to inform that a recipe was not working as intended.

**Comment by macmule** [comment]
fair enough, thanks for the warning & the requires has been removed.
