### ISSUE TITLE
FortiClientVPN6.download.recipe filename changed 

### ISSUE THREAD

**Issue by MichalMMac** [autopkg/dataJAR-recipes#54]
Filename changed to `FortiClientVPNOnlineInstaller_6.2.dmg` 
Download recipe needs an udpate.

https://github.com/autopkg/dataJAR-recipes/blob/c1021788a0734042be0f21254587edaac883e174/Forticlient/FortiClientVPN6.download.recipe#L30

**Comment by Daz-wallace** [comment]
Thanks @MichalMMac should be all resolved!

**Comment by MichalMMac** [comment]
Wow. That was fast. I didn't even get to making my own PR. Thanks @Daz-wallace ! :-)
