### ISSUE TITLE
Adobe 2020 - Display Name

### ISSUE THREAD

**Issue by eshirk** [autopkg/dataJAR-recipes#58]
Any chance that there's a low-impact way to modify Adobe2020Versioner.py so that it respects the recipe override's pkginfo display_name if one is present?

Use case: we package both named-user and shared-device-license versions of each title and so need that info in the display name, but the versioner is imposing display name of app_path + ' 2020'.

Many thanks for this time-saving tool.

**Comment by macmule** [comment]
@eshirk why not use the named-user pkg then install the shared-device-license pkg (as in the license itself), post?

**Comment by eshirk** [comment]
Good question; the short answer is that because of the size and scope of our campus-wide multi-tenant Munki service, along with our quest for service parity with our SCCM service, we landed on separate packages for each license model.

**Comment by Daz-wallace** [comment]
@eshirk We'd suggest that you create Unlicensed / NUL licensed packages and then import an SDL package separately. You can apply the SDL to the devices that need it to convert the deployment as needed.

That way you only need to create, package, store and update one package per App, rather than two per app.

**Comment by eshirk** [comment]
We will probably move to this model for the 2021 release, but we'll still need to edit the display_name value in the unlicensed/NUL pkginfo file for the sake of clarity, for the IT Pros who use our service.

**Comment by macmule** [comment]
@eshirk Pull Requests glady accepted, but these recipes have worked this way since 2018 & are currently working for us & many others as they are.

As such, I'm closing this one off for now as we're likely not to make the changes requested here ourselves.
