### ISSUE TITLE
Issue with download on FortiClientVPN6.download.recipe

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#60]
Looks like the website is down or taken offline - https://www.forticlient.com/downloads  

Full error:```

 u'SEARCH_URL': u'https://www.forticlient.com/downloads',
 u'USER_AGENT': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9',
 'verbose': 3}
URLTextSearcher
{'Input': {'re_pattern': u'https://filestore.fortinet.com/forticlient/downloads/FortiClientVPNOnlineInstaller_6.[\\S].dmg',
           'request_headers': {
    "user-agent" = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9";
},
           'url': u'https://www.forticlient.com/downloads'}}
URLTextSearcher: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
URLTextSearcher: No value supplied for result_output_var_name, setting default value of: match
curl failure: % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to www.forticlient.com port 443: Connection refused (exit code 7)
Failed.
Receipt written to /Users/darren/Library/AutoPkg/Cache/com.github.dataJAR-recipes.download.forticlientvpn/receipts/FortiClientVPN6.download-receipt-20200109-125841.plist

The following recipes failed:
    FortiClientVPN6.download.recipe

        Error in com.github.dataJAR-recipes.download.forticlientvpn: Processor: URLTextSearcher: Error: curl failure: % Received % Xferd  Average Speed   Time    Time     Time  Current
                                         Dload  Upload   Total   Spent    Left  Speed
        
          0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to www.forticlient.com port 443: Connection refused (exit code 7)

Nothing downloaded, packaged or imported.```

This may have moved to https://www.fortinet.com/demand/gated/forticlient-mac-download.html 

Use a throwaway email address to get a download link of http://fortinetweb.s3.amazonaws.com/forticlient/downloads/FortiClientOnlineInstaller.dmg  but this downloads a DMG of an online installer App which downloads the installer.

Need to run this through something else to extract the URL and see if we can use it.

**Comment by Daz-wallace** [comment]
Looks like it was a temporary outage on the site but the download still extracts the new online installer App which downloads the installer.

**Comment by MichalMMac** [comment]
I saw the latest change. `FortiClient is only available via an Online Installer app, can no longer be mass deployed.`.

Is this bacause of the license or we just don't have URL for actual install dmg?

**Comment by neilmartin83** [comment]
Fortinet changed the DMG containing the installer so that it now contains an app that will download the installer package over the internet.

The previous DMG had the package hidden away in the app bundle, which Autopkg could extract and import into Munki etc.

I'm afraid that's no longer possible because of this change.

**Comment by macmule** [comment]
So.. i've deprecated this recipe as "FortiClient is only available via an Online Installer app, can no longer be mass deployed."

If folks need this, I suggest reaching out to Fortinet to ask for an Offline Installer

**Comment by MichalMMac** [comment]
The new FortiClient "download installer" downloads .dmg with .mpkg package to the cache in /private/var/folder. I wonder where it gets it.
