### ISSUE TITLE
Rectangle JSS recipe creates policy as "Webrecorder Player"

### ISSUE THREAD

**Issue by smashism** [autopkg/dataJAR-recipes#64]
I imagine this is a copy/paste oversight

https://github.com/autopkg/dataJAR-recipes/blob/5a98b0c3ac05fe3666b04b750e00f430ef52698d/Rectangle/Rectangle.jss.recipe#L55

I don't appear to have the permissions to do a PR but this seems like a pretty straight-forward fix.

**Comment by Daz-wallace** [comment]
I’ll jump on this as soon as I reach a desk. Thanks for the spot

**Comment by Daz-wallace** [comment]
Hi @smashism 

Sorry about the bad copy/paste. That's 100% my fault.

[Fix committed](https://github.com/autopkg/dataJAR-recipes/commit/ef9b1c0a74a4271feed8f9b42ba39d03db29c41e). 

Any problems, please let us know.
