### ISSUE TITLE
BoxDrive.jss.recipe failing with Unknown processor 'PkgInfo'

### ISSUE THREAD

**Issue by mpanighetti** [autopkg/dataJAR-recipes#68]
BoxDrive.jss.recipe is failing with error: `Unknown processor 'PkgInfo'.` [It looks like the `PkgInfo` processor was removed yesterday](https://github.com/autopkg/dataJAR-recipes/commit/5c73b6ec79ef4503923b3aff7a61db4079215e9b#diff-40195e60a26f64bddca7c2d22d8f52f7) which would explain the disconnect.

**Comment by macmule** [comment]
Apologies, missed that one when making the changes yesterday.

Should be sorted now, please update the repo & if any issues please reach out again.

**Comment by mpanighetti** [comment]
That fixed it, thanks!
