### ISSUE TITLE
Error when running SketchUp Pro 2018 EN recipe

### ISSUE THREAD

**Issue by gigiwest123** [autopkg/dataJAR-recipes#7]
No match found on URL: https://www.sketchup.com/download/all

Not sure if I'm missing a step, or if the link has changed, the URL seems to direct to the downloads page, just a bit stuck.

Thanks

**Comment by macmule** [comment]
@gigiwest123 just seen the issue myself.. bare with :)

**Comment by macmule** [comment]
@gigiwest123 should be resolved now in https://github.com/autopkg/dataJAR-recipes/commit/fcddec230507b36f503c45092635193cb6c540b4
