### ISSUE TITLE
Problem with AmazonCorrettoJava8.munki

### ISSUE THREAD

**Issue by GordSpence** [autopkg/dataJAR-recipes#70]
Recently the Amazon Corretto recipe has been failing with the following error which appears to be related to the SEARCH_PATTERN:

>         Error in local.munki.AmazonCorrettoJava8: Processor: URLTextSearcher: Error: No match found on URL: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

I'm not sure what's going wrong and I've even tried manually specifying the full address for the download in the search pattern, but that's not working either. Hoping someone smarter than me is able to narrow down the problem.

**Comment by macmule** [comment]
So.. ours looks at https://github.com/autopkg/dataJAR-recipes/blob/master/AmazonCorrettoJDK/AmazonCorrettoJava8.munki.recipe#L50 as a parent.. 

Will need to check there & whatever that uses.. thanks though.. will look tomorrow :)

**Comment by macmule** [comment]
@GordSpence can you update your overrides SEARCH_URL?

```
		<key>SEARCH_URL</key>
		<string>https://github.com/corretto/corretto-8/releases/latest</string>
```

The above is set in our override, & seems to be working.

**Comment by GordSpence** [comment]
That definitely does work for me - just got the latest to download

**Comment by macmule** [comment]
Awesome, thanks for letting us know.
