### ISSUE TITLE
VMware Fusion 11 - processor path not found for processor

### ISSUE THREAD

**Issue by master-vodawagner** [autopkg/dataJAR-recipes#71]
Getting the following errors when running this recipe on AutoPkg 2.0.1

autopkg run VMwareFusion11-update.jss.recipe -vvvv
Processing VMwareFusion11-update.jss.recipe...
WARNING: processor path not found for processor
Failed.
Receipt written to /tmp/receipts/VMwareFusion11-update.jss-receipt-20200220-155000.plist

The following recipes failed:
    VMwareFusion11-update.jss.recipe
        Unknown processor 'com.justinrummel.download.VMwareFusion/VMwareFusionURLProvider'.

**Comment by macmule** [comment]
@master-vodawagner you need to add the justinrummel repo to AutoPkg, as we’re using their processor now
