### ISSUE TITLE
Luxafor

### ISSUE THREAD

**Issue by macmule** [autopkg/dataJAR-recipes#72]
Download hosted at https://prev.luxafor.com/uploads/ which is using an expired self-signed cert.

Presuming temporary.

**Comment by Daz-wallace** [comment]
Same issue still present.

Looks like the actual download links on https://luxafor.com/download/ are HTTP not HTTPS. 
Can't see any option to log support details so sent a tweet - https://twitter.com/Daz_Wallace/status/1231991337580408832?s=20

**Comment by Daz-wallace** [comment]
Email address provided by the twitter feed - support@luxafor.com

Email sent asking them to sort out the download page's cert. Looks like it's self-signed, out of date and for the wrong domain (maybe).

**Comment by Daz-wallace** [comment]
Reply from their support:

> Hello Darren,
> 
> Thanks so much for reaching out and letting us know!
> 
> We are in the middle of changing our hosting services and the domain, and thus we currently only hold the certificate you mentioned, and we are looking into resolving this as soon as possible.
> As for your customers to be able to download our software right now feel free to use this link: https://www.dropbox.com/sh/pj6lnki5ypqz1t7/AABjDcmyUoxPXcM4tmChjqf2a?dl=0
> 
> Wishing you a great weekend,


I think we'll wait for them to fix it....

**Comment by Daz-wallace** [comment]
The vender has fixed this now (yaa!)
