### ISSUE TITLE
Suitcase Fusion 21

### ISSUE THREAD

**Issue by prausch** [autopkg/dataJAR-recipes#75]
Suitcase Fusion 9 has been replaced with Suitcase Fusion 21, and a Sparkle feed is present

https://sparkle.extensis.com/u/ST/EN/suitcase21en.xml

**Comment by neilmartin83** [comment]
Thanks - fixed in commit https://github.com/autopkg/dataJAR-recipes/commit/a475eec8f375d3e512ee056b000471d7cb2afdbc

Suitcase Fusion 21 recipes are here: https://github.com/autopkg/dataJAR-recipes/tree/master/Suitcase%20Fusion%2021

:-)
