### ISSUE TITLE
Framer X recipe not spotting new versions

### ISSUE THREAD

**Issue by jelockwood** [autopkg/dataJAR-recipes#76]
It looks like your Framer X recipe stopped working at V48 in December 2019 and has as a result not spotted V49 or V50. (V50 is the current version.)

I removed all the previously download/generated files from ~/Library/AutoPkg/Cache to force it to run a completely fresh check and it did re-download a file but when I examined the result it was still V48 and not the current V50.

It seems your recipe is only finding and download V48 and not the current version. This would suggest a fault in your regex although I may be wrong.

Since it is downloading a version AutoPkg gives no errors, AutoPkg does not know it is the wrong out of date version.

**Comment by neilmartin83** [comment]
Thanks for letting us know - this is fixed now in commit https://github.com/autopkg/dataJAR-recipes/commit/96adeac1c665e85ae77aa1bf16d0869991d099ee 👍

**Comment by jelockwood** [comment]
@neilmartin83 Thanks for the rapid fix. I can confirm it now works for me.
