### ISSUE TITLE
WatchGuard Mobile VPN with SSL admin prompt

### ISSUE THREAD

**Issue by ewancolyer** [autopkg/dataJAR-recipes#78]
Not so much an issue with the recipe its self, but after running and installing on a mac running Mojave (10.14.6) it prompts to make changes. If you dismiss these then try to use the VPN you get the attached error.

<img width="445" alt="Screenshot 2020-03-20 at 11 18 56" src="https://user-images.githubusercontent.com/32178903/77162456-e9073a80-6aa3-11ea-8a13-4e6e3f22904b.png">

**Comment by neilmartin83** [comment]
Hey @ewancolyer ,

Are you whitelisting the kernel extension for this before you install?

The developer ID should be KS8XL6T9FZ (haven't tested).

https://help.endian.com/hc/en-us/articles/360019434774-How-to-Fix-Cannot-allocate-TUN-TAP-dev-dynamically-error-on-MAC-OS-X

**Comment by ewancolyer** [comment]
Hey @neilmartin83 :)

I've got 84ZK5S5258 as the developer ID for watchguard that i'm whitelisting

**Comment by neilmartin83** [comment]
Ah - did this one work then?

**Comment by ewancolyer** [comment]
No, its still prompting to make changes with that allowed.

I'm just testing it with a fresh VM, manually allowing the kext and checking that it is the correct one.

**Comment by neilmartin83** [comment]
I'll have a try in a VM here - we're deploying it for a customer and whitelisting 84ZK5S5258 as well. Stand by!

**Comment by neilmartin83** [comment]
Hi Ewan,

I installed this and am seeing the admin prompt. Might be able to suppress it with a munki postinstall script... digging in to see what it does.

**Comment by neilmartin83** [comment]
Hey Ewan,

Afraid I couldn't find a way around this - the app tries to run a script that sets permissions on a couple of binaries in the app bundle but when I do that manually, it still prompts. Did you see anything at all in the vendor docs? I had a brief look but only found a page that said it would prompt for admin... grr!

Might be worth giving their support a nudge.

**Comment by ewancolyer** [comment]
I'll get in contact with their support, from a quick look it looks like you can use openVPN instead of their client so I may investigate that.

I'll leave it upto you guys if you want keep the issue open or not.

**Comment by neilmartin83** [comment]
Cheers - I'll close this one as it's more a vendor issue.

For OpenVPN, Tunnelblick and OpenVPN Connect Client could work. Tunnelblick definitely doesn't need admin creds on launch if you use the autopkg recipes for it. And you can package/deploy your org's config for it pretty easily.

Have a great weekend!
