### ISSUE TITLE
VMware Fusion 11.download.recipe is creating a broken App

### ISSUE THREAD

**Issue by beatlemike** [autopkg/dataJAR-recipes#79]
The app that download says it is damaged. 

![Screen Shot 2020-03-25 at 6 40 00 PM](https://user-images.githubusercontent.com/31707108/77601461-0daa4a80-6ec8-11ea-997f-9cf02746cc85.png)

**Comment by Daz-wallace** [comment]
Possibly linked to this https://github.com/autopkg/justinrummel-recipes/issues/23

**Comment by Daz-wallace** [comment]
@beatlemike Are you deploying the output of the .download recipe, or the .pkg recipe?

**Comment by beatlemike** [comment]
@Daz-wallace Hi Darren! normally I uses a custom JSS to the .pkg recipe, but when I noticed it was pulling a damaged app, I tried an override to the .pkg recipe directly with the same result. Then I just ran the .download directly, which after some unzipping , yielded the same result. 

If I recall isn't the data-jar recipe based off the justinrummel .download recipe? That actually works, but none of his other ones yield an undamaged app.

I tried checking permissions between the undamaged app, and the damaged app and I can't see anything, But beyond that I'm at a loss as to what is causing the error.

**Comment by Daz-wallace** [comment]
@beatlemike The download .app may be undamaged but to deploy it needs a bit more work. So a download recipe that downloads a valid App may still not work once deployed.

We'll take a look at this but I suspect it needs some other magic :/

**Comment by beatlemike** [comment]
Thanks @Daz-wallace I assumed there might be some mystic doings that I am not learned enough to figure out. I'm guessing I can't be the only one it's come down for, took me, I think, two days to even notice though

**Comment by Daz-wallace** [comment]
Hi @beatlemike 

I've just re-tested our recipe and installed this into a VM and VMware Fusion 11 launched fine (with all the usual PPPC and license code prompts).

Can you retest with a fresh package / .pkg recipe?
Also, do you have the issue in a fresh install, or only when updating an existing install?

**Comment by beatlemike** [comment]
Hi @Daz-wallace 
I feel like an idiot now, but this morning it works just fine. The issue before was first noticed on a clean install. It was tested after that yesterday and the day before on both a clean VM and my own machine an update.

If there was an issue maybe it wasn't on your end at all haha Alright, cool thanks for helping me troubleshoot though, I know you are super busy.

Mike

**Comment by Daz-wallace** [comment]
Hi @beatlemike 
It could be VMWare had a bad release?

No harm anyway! Glad it seems to be working now.

Have a great weekend and stay safe!
