### ISSUE TITLE
JumpCloud Agent.munki.recipe results in re-installation after auto update

### ISSUE THREAD

**Issue by wholtz** [autopkg/dataJAR-recipes#8]
The JumpCloud Agent performs automatic updates. The installs array created by MunkiInstallsItemsCreator for this program is checksum based. So after an auto-update occurs by the JumpCloud agent, Munki notices the checksum no longer matches and re-installs the most current version in the Munki repo. Therefore if your Munki repo is a bit behind the current JumpCloud release, you'll get thrashing between versions as JumpCloud Agent and Munki disagree about what version should be installed.

When these auto updates by the JumpCloud Agent occur, the receipt information is updated. However, the installs array that takes precedence over the receipt information. I believe removing the MunkiInstallsItemsCreator Processor step will fix this issue.

**Comment by macmule** [comment]
@wholtz Sounds reasonable, can you submit a PR with changes?

**Comment by macmule** [comment]
resolved in #9
