### ISSUE TITLE
Abstract Download Error

### ISSUE THREAD

**Issue by eclears** [autopkg/dataJAR-recipes#81]
Error with Abstract in autopkg:

Error running recipes

Not match found on URL: https://api.goabstract.com/releases/latest
Failed.

**Comment by macmule** [comment]
@eclears have you updated our repo? 

https://github.com/autopkg/dataJAR-recipes/blob/master/Abstract/Abstract.download.recipe

was updated 17 days ago

**Comment by eclears** [comment]
Oops! Resolved!
