### ISSUE TITLE
Deprecate and remove CrashPlanPROeClient.munki.recipe

### ISSUE THREAD

**Issue by n8felton** [autopkg/dataJAR-recipes#82]
CrashPlan PROe has been rebranded as Code42 for Enterprise (or Code42 CrashPlan?). This recipe no longer works as the values it's looking for (`cp.download.CPPROE_CLIENT_VERSION`) no longer exist.

As a cleanup item, I suggest at a minimum adding a DeprecationWarning to this, but recommend just removing the recipe entirely as it likely hasn't worked for a number of months at this point.

**Comment by macmule** [comment]
Depreacted as parent pkg recipe was deleted: https://github.com/autopkg/homebysix-recipes/commit/a8bef0ee56626811992dac34c639122c618d75ab#diff-ce0b34293223285eb9810a1219e7ff05
    
Thanks for the heads up
