### ISSUE TITLE
FreeFileSync.download - CodeSignatureVerifier fails

### ISSUE THREAD

**Issue by andredb90** [autopkg/dataJAR-recipes#85]
Hi

I noticed that your FreeFileSync.download recipe throws an error. 

The input path is set to FreeFileSync_10.14_macOS.pkg. The version is now 10.23 and is likely to change again.

**Comment by neilmartin83** [comment]
Thanks @andredb90 - fixed in commit: https://github.com/autopkg/dataJAR-recipes/commit/d7fc8b5c9821ad33d8417b639433a88afd98de42

**Comment by andredb90** [comment]
hi @neilmartin83 

Thanks for taking actions so quickly! 

It looks like FreeFileSync.pkg has now a similar issue with its use of PlistReader.

The following recipes failed:
    FreeFileSync.pkg
        Error in local.pkg.FreeFileSync: Processor: PlistReader: Error: Path '/Users/admin/Library/AutoPkg/Cache/local.pkg.FreeFileSync/FreeFileSync/Applications/FreeFileSync.app' doesn't exist!

**Comment by neilmartin83** [comment]
Hi @andredb90 I've re-done the pkg recipe so it:

1. Unpacks the extracted flat package from the download recipe (this will work as long as the package is named "FreeFileSync*.pkg").
2. From the unpacked flat package, unpacks the component package, "FreeFileSync.pkg"'s payload. 
3. Grabs the correct version from the app bundle in the unpacked FreeFileSync.pkg component package payload.
4. Copies the extracted flat package from step 1, appending the correct version to the filename.

I also checked the munki recipe which uses the pkg recipe as its parent, and it works properly for me.

Please give it a try and let me know how you get on! :-)

**Comment by neilmartin83** [comment]
https://github.com/autopkg/dataJAR-recipes/commit/a38da23b8b73030f5d52195e4b3519f22a507373

**Comment by andredb90** [comment]
Hi @neilmartin83 

Great job, thank you! I ran the recipes and everything worked as expected. (including my FreeFileSync.filewave recipe)
