### ISSUE TITLE
Cisco Webex Meetings.download.recipe keeps downloading an old version

### ISSUE THREAD

**Issue by jby** [autopkg/dataJAR-recipes#87]
This recipe always downloads version 40.2.18.5...

**Comment by jby** [comment]
Current version is 40.4.5 AFAIK

**Comment by jby** [comment]
Ok, it seems that the 40.2.18.5 is what you get if you go to download it from their site as well, so maybe not that strange that your recipe downloads that version...

**Comment by neilmartin83** [comment]
Hey @jby how are you getting 40.4.5?

**Comment by jby** [comment]
> Hey @jby how are you getting 40.4.5?

Let me find out - I just had to reboot my Mac due to AppStore hanging

**Comment by jby** [comment]
I seem to have gotten that using this recipe on May 1:

``` 
local.munki-receipt-20200501-072428.plist:                      <string>/Users/jonasb/Library/AutoPkg/Cache/local.munki.Cisco Webex Meetings/Cisco Webex Meetings-40.4.5.5.pkg</string>
```
local.munki.Cisco Webex Meetings being my local override of this recipe...

**Comment by neilmartin83** [comment]
We read the version from `Cisco Webex Meetings.app/Contents/Info.plist` --> `CFBundleShortVersionString`

So for whatever reason, the current download is a lower version than before... 40.2.18.5

I'll close this as it's a vendor issue, unfortunately not much else we can do.

Thanks for the heads up!

**Comment by jby** [comment]
Yeah, ok!

**Comment by SilentHunter124** [comment]
Can we reopen this ticket? The Webex Portal has download URLS with specific version matrix.
