### ISSUE TITLE
Fix extension attribute shebang

### ISSUE THREAD

**Issue by pythoninthegrass** [autopkg/dataJAR-recipes#93]
This script for the Box Drive EA has a typo which causes `jamf recon` to fail.
https://github.com/autopkg/dataJAR-recipes/blob/1c7a5ade5ec8507b2dd77f6b0c64f2effa2adb4e/BoxDrive/BoxDrive-ExtensionAttribute.xml#L8

Just need to switch `#!/bin/assh` to `#!/bin/bash`. If you'd like, I can try a pull request.

**Comment by macmule** [comment]
@pythoninthegrass please try a pull request :)

**Comment by pythoninthegrass** [comment]
@macmule Done. Let me know if you need anything else ^_^

**Comment by neilmartin83** [comment]
Merged PR, thanks!
