### ISSUE TITLE
Adobe 2020 recipe errors

### ISSUE THREAD

**Issue by georgecm12** [autopkg/dataJAR-recipes#95]
I am receiving errors attempting to run the Adobe 2020 Import.jss.recipe, with overrides for AfterEffects2020, Photoshop2020, PremierePro2020, Animate2020, and DImension2020.

For the first four, the error reported is "JSSImporter: Error: string longer than 2147483647 bytes". A redacted -vvv output from the recipe run for AfterEffects2020 is attached. (Photoshop2020, PremierePro2020, and Animate2020 have almost identical output.

For Dimension2020, the error is "Adobe2020Versioner: Error: not well-formed (invalid token): line 1, column 0". A redacted -vvv output from the recipe run for Dimension2020 is also attached.

Any suggestions are welcome.
[AdobeDimension2020.jss Output.txt](https://github.com/autopkg/dataJAR-recipes/files/4921830/AdobeDimension2020.jss.Output.txt)
[AdobeAfterEffects2020.jss Output.txt](https://github.com/autopkg/dataJAR-recipes/files/4921670/AdobeAfterEffects2020.jss.Output.txt)

**Comment by Daz-wallace** [comment]
Hi @georgecm12 

I'm just grabbing fresh copies of the installers to see what the issue might be.

Did these recipes work fine previously or not? If so, is it just newer Adobe packages that have changed to break it?

**Comment by Daz-wallace** [comment]
Ah just seen your comments in JSS-Importer on Slack.

It would suggest the first four installers with the error "JSSImporter: Error: string longer than 2147483647 bytes" could be related to Jamf and / or JSSImporter?

I'll look into the Dimension issue but this might be an issue reported with Dimension's info.plist file.

**Comment by Daz-wallace** [comment]
With Hyper drive (which is most of the) Adobe Apps we're reading the location of the App versions from:
./[App title].pkg/Contents/Resources/HD/[SAP Code][majorversion]/*.zip

For other Apps this works fine and you can actually unzip the file in the Finder. For Dimension this fails on the versioner script and fails to unzip in Finder.

I'll do some more digging...

**Comment by Daz-wallace** [comment]
So the bash tool 'unzip' and Stuffit Expander and expand the zip fine, but the info.plist file inside the zipped file is garbage.

This is looking like it could be an Adobe issue :/

**Comment by Daz-wallace** [comment]
Hi George,
 The Dimension issue is a bit trickier. I've logged that under #96 so we can close this but at the moment, its a fix needed from Adobe :/
