### ISSUE TITLE
Adobe Dimension 2020 has issues with Adobe Versioner

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/dataJAR-recipes#96]
**Issue:**
When running the AutoPKG recipes for Adobe 2020 on Dimension 2020 it fails with the error:
"Adobe2020Versioner: Error: not well-formed (invalid token): line 1, column 0"

**Expected:**
Versioner should be able to pull the correct App version out of the package payload and pass this through the processor list to where its needed, same as it will do for the other Adobe 2020 Apps

**Actual:**
This fails with the error "Adobe2020Versioner: Error: not well-formed (invalid token): line 1, column 0".
The installer package will still install correctly and the Application function normally once installed

**Cause:**
Although not confirmed, it appears to be an issue with the .zip file generated that holds the Application.
This is located at `./[Dimension Package]_Install.pkg/Contents/Resources/HD/ESHR3.3/AdobeDimension1-core.zip`
This fails to unzip in the Finder, or via a python unzip command, but the same respective location for other Adobe application packages unzips fine and they'll work fine.
The Dimension zip  _can_ be unzipped successfully via bash unzip or via Stuffit Expander
Once unzipped, the info.plist file inside the Application bundle is still garbage and not usable.
This file looks fine inside the application bundle once installed.

This will need a fix / change from Adobe, which might not be forthcoming

**Comment by moorereason** [comment]
I'm seeing this problem with Dimension and Bridge.  The pimx is not a plain XML file.  Looking at the hexdumps below, the files are similar.  Wondering if they're encoding the package in an unknown format.

```
$ find -E ~/Downloads -type f -regex '.*AdobeBridge[^/]+-(mul|core).zip'
/Users/x/Downloads/AdobeBridge2021/Build/AdobeBridge2021_Install.pkg/Contents/Resources/HD/KBRG11.0.1/AdobeBridge11.0-mul.zip

$ ditto -xk ~/Downloads/AdobeBridge2021/Build/AdobeBridge2021_Install.pkg/Contents/Resources/HD/KBRG11.0.1/AdobeBridge11.0-mul.zip bridge-tmp

$ file bridge-tmp/AdobeBridge11.0-mul.pimx
bridge-tmp/AdobeBridge11.0-mul.pimx: data

$ hexdump -C bridge-tmp/AdobeBridge11.0-mul.pimx | head -7
00000000  18 e0 0f d5 02 aa 5d 00  1e 0f cb 87 11 d8 ce 66  |......]........f|
00000010  91 0f 83 1e ca fd 7b 33  d4 7f e9 b7 da 28 31 76  |......{3.....(1v|
00000020  25 66 20 4d 2a 09 6d 6a  f7 29 70 38 41 13 95 08  |%f M*.mj.)p8A...|
00000030  8a d0 5b 1d 93 4b e2 52  86 85 0b f7 2a bf c6 55  |..[..K.R....*..U|
00000040  4f a5 1f c8 d1 11 61 59  97 b1 21 9d 4e 20 a8 37  |O.....aY..!.N .7|
00000050  45 65 1f 89 ea 8d d4 f6  e9 ee 39 bc 17 e8 56 b9  |Ee........9...V.|
00000060  a6 17 d8 2f a5 38 e6 a3  c8 87 7d 79 e7 c1 7e 4d  |.../.8....}y..~M|
```

Here's the same for the Adobe Dimension:

```
$ find -E ~/Downloads -type f -regex '.*AdobeDimension[^/]+-(mul|core).zip'
/Users/x/Downloads/AdobeDimension2020/Build/AdobeDimension2020_Install.pkg/Contents/Resources/HD/ESHR3.4.1/AdobeDimension1-core.zip

$ ditto -xk /Users/x/Downloads/AdobeDimension2020/Build/AdobeDimension2020_Install.pkg/Contents/Resources/HD/ESHR3.4.1/AdobeDimension1-core.zip dimension-tmp

$ file dimension-tmp/AdobeDimension1-core.pimx
dimension-tmp/AdobeDimension1-core.pimx: data

$ hexdump -C dimension-tmp/AdobeDimension1-core.pimx | head -7
00000000  18 e0 03 6d 01 76 5d 00  1e 0f cb 87 11 d8 ce 66  |...m.v]........f|
00000010  91 0f 83 1e ca fd 7b 33  d4 7f e9 b7 da 28 31 76  |......{3.....(1v|
00000020  25 66 20 4d 2a 09 6d 6a  f7 29 70 38 41 13 95 08  |%f M*.mj.)p8A...|
00000030  8a d0 5b 1d 93 4b e2 52  86 85 0b f7 2a bf c6 55  |..[..K.R....*..U|
00000040  4f a5 1f c8 d1 11 61 59  97 b1 21 9d 4e 20 a8 37  |O.....aY..!.N .7|
00000050  45 65 1f 89 ea 8d d4 f6  e9 ee 39 bc 17 e8 56 b9  |Ee........9...V.|
00000060  a6 17 d8 2f a5 39 1e d1  0e 19 dc 1d 45 e8 15 4c  |.../.9......E..L|
```

**Comment by neilmartin83** [comment]
Confirmed the issue is now with Dimension and Bridge :-(

**Comment by Daz-wallace** [comment]
Case logged with Adobe 🤞 
Case ID: E-00032579

**Comment by Daz-wallace** [comment]
Any un-named helper has suggested that there's a JSON file we can also get this information from, e.g. in Bridge:
`Build/Bridge\ 11.0.1_Install.pkg/Contents/Resources/HD/KBRG11.0.1/Application.json`

Going through this JSON it looks like it has the version information we need, e.g. for Dimension:
```
   "CodexVersion":"3.4.1",
   "AssetGuid":"30ea4f4f-0f7e-4a84-9583-a9cda9d81c84",
   "ProductVersion":"3.4.1.3482",
```

We should be able to pull this and use it.

We're thinking of maybe line [213](https://github.com/autopkg/dataJAR-recipes/blob/master/Adobe%202021/Adobe2021Versioner.py#L213) in the versioner script to try the unzip, if this errors try the JSON.

We'll get to the group when we have something together 😊
