### ISSUE TITLE
curl SSL error from Jump Desktop Connect munki recipe

### ISSUE THREAD

**Issue by jw-macworks** [autopkg/dataJAR-recipes#98]
mirror.jumpdesktop.com certificate appears to be valid.
Issued by: Sectigo RSA Domain Validation Secure Server CA
Expires: Monday, March 29, 2021 at 4:59:59 PM Pacific Daylight Time

curl (7.54.0) returns 
curl: (60) SSL certificate problem: certificate has expired

Autopkg (2.1) returns
Error in local.munki.Jump Desktop Connect: Processor: URLDownloader: Error: Command '['/usr/bin/curl', '--silent', '--show-error', '--no-buffer', '--dump-header', '-', '--speed-time', '30', '--location', '--url', 'https://mirror.jumpdesktop.com/downloads/connect/JumpDesktopConnect-6.3.39.dmg', '--fail', '--output', '/Volumes/Repositories/Munki/AutoPkg/Cache/local.munki.Jump Desktop Connect/downloads/tmpi3ay5pb6', '--header', 'If-None-Match: "0721a9727b1fdd31922469a3012b452f-3"', '--header', 'If-Modified-Since: Thu, 30 Apr 2020 17:30:36 GMT']' returned non-zero exit status 60.

**Comment by Daz-wallace** [comment]
Hi @jw-macworks 
I'm not able to replicate the issue this side, either with the .download or .munki recipes.

Can you try again to see if you hit a temporary problem?
Do you have a proxy on your AutoPKG box, either specific or inline?
Is it also possible you're hitting this - https://macmule.com/2020/06/02/autopkg-curl-exit-status-60/ ?

**Comment by neilmartin83** [comment]
Hey @jw-macworks - as well as the solution @Daz-wallace linked to above (removing the CA cert entry manually), this is also fixed in macOS 10.15.6... https://support.apple.com/en-us/HT210642

> Allows command-line tools that don't use CFNetwork, such as curl(1), to continue connecting to TLS servers that use certificates issued by the recently expired AddTrust External CA Root

**Comment by jw-macworks** [comment]
Thank you both. That makes sense.
